/* basis/compiler/machineCode.c */
int32 _CalculateModRmByte(int32 mod, int32 reg, int32 rm, int32 disp, int32 sib);
void _Compile_Displacement(int32 modRm, int32 disp);
int32 _CalculateSib(int32 scale, int32 indexReg, int32 baseReg);
void _Compile_ModRmSibDisplacement(int32 modRm, int32 modRmFlag, int32 sib, int disp);
void _Compile_ImmediateData(int32 imm, int32 immSize);
void Compile_StartOpCode_Int8(int opCode);
void _Compile_InstructionX86(int opCode, int mod, int reg, int rm, int modFlag, int sib, int32 disp, int32 imm, int immSize);
void _Compile_LEA(int32 reg, int32 rm, int32 sib, int32 disp);
void _Compile_X_Group1(int32 code, int32 toRegOrMem, int32 mod, int32 reg, int32 rm, int32 sib, int32 disp, int32 osize);
void _Compile_X_Group1_Immediate(int32 code, int32 mod, int32 rm, int32 disp, int32 imm, int32 iSize);
void _Compile_Op_Group1_Reg_To_Reg(int32 code, int32 dstReg, int32 srcReg);
void _Compile_Op_Special_Reg_To_Reg(int32 code, int32 rm, int32 reg);
void _Compile_Group2(int mod, int regOpCode, int rm, int sib, int32 disp, int32 imm);
void _Compile_Group2_CL(int mod, int regOpCode, int rm, int sib, int32 disp);
void _Compile_Group3(int32 code, int32 mod, int32 rm, int32 sib, int32 disp, int32 imm, int32 size);
void _Compile_IMULI(int32 mod, int32 reg, int32 rm, int32 sib, int32 disp, int32 imm, int32 size);
void _Compile_IMUL(int32 mod, int32 reg, int32 rm, int32 sib, int32 disp);
void _Compile_Test(int32 mod, int32 reg, int32 rm, int32 disp, int32 imm);
void _Compile_Group5(int32 code, int32 mod, int32 rm, int32 sib, int32 disp, int32 size);
void _Compile_Move_Reg_To_Reg(int32 dstReg, int32 srcReg);
void _Compile_MoveImm(int32 direction, int32 rm, int32 sib, int32 disp, int32 imm, int32 operandSize);
void _Compile_MoveImm_To_Reg(int32 reg, int32 imm, int32 iSize);
void _Compile_MoveImm_To_Mem(int32 reg, int32 imm, int32 iSize);
void _Compile_MoveMem_To_Reg(int32 reg, byte *address, int32 thruReg, int32 iSize);
void _Compile_MoveMem_To_Reg_NoThru(int32 reg, byte *address, int32 iSize);
void _Compile_MoveReg_To_Mem(int32 reg, byte *address, int32 thruReg, int32 iSize);
void _Compile_Move(int32 direction, int32 reg, int32 rm, int32 sib, int32 disp);
void _Compile_Move_Reg_To_Rm(int32 dstRmReg, int32 srcReg, int32 disp);
void _Compile_Move_AddressValue_To_EAX(int32 address);
void _Compile_Move_EAX_To_MemoryAddress(int32 address);
void _Compile_Move_Rm_To_Reg(int32 dstReg, int32 srcRmReg, int32 disp);
byte *Calculate_Address_FromOffset_ForCallOrJump(byte *address);
int32 _CalculateOffsetForCallOrJump(byte *compileAtAddress, byte *jmpToAddr);
void _SetOffsetForCallOrJump(byte *compileAtAddress, byte *jmpToAddr);
void _Compile_JumpToAddress(byte *jmpToAddr);
void _Compile_JumpToReg(int32 reg);
void _Compile_UninitializedJumpEqualZero(void);
void _Compile_JumpWithOffset(int32 disp);
void _Compile_UninitializedCall(void);
void _Compile_UninitializedJump(void);
void _Compile_JCC(int32 negFlag, int32 ttt, uint32 disp);
void Compile_JCC(int32 negFlag, int32 ttt, byte *jmpToAddr);
void _Compile_Call(int32 callAddr);
void Compile_Call(byte *callAddr);
void _Compile_Call_NoOptimize(byte *callAddr);
void _Compile_TEST_Reg_To_Reg(int32 dstReg, int32 srcReg);
void _Compile_Return(void);
void _Compile_PushReg(int32 reg);
void _Compile_PopToReg(int32 reg);
void _Compile_PopAD(void);
void _Compile_PushAD(void);
void _Compile_PopFD(void);
void _Compile_PushFD(void);
void _Compile_Sahf(void);
void _Compile_Lahf(void);
void _Compile_IRET(void);
void _Compile_INT3(void);
void _Compile_INT80(void);
void _Compile_Noop(void);
void _Compile_MOVZX_REG(int32 reg);
void Compile_X_Group5(Compiler *compiler, int32 op);
void _Compile_optInfo_X_Group1(Compiler *compiler, int32 op);
void Compile_X_Group1(Compiler *compiler, int32 op, int32 ttt, int32 n);
void _Compile_Jcc(int32 bindex, int32 overwriteFlag, int32 nz, int32 ttt);
/* basis/compiler/_compile.c */
void _Compile_CallEAX(void);
void Compile_DataStack_PopAndCall(void);
void _Compile_Rsp_To(void);
void _Compile_Rsp_Drop(void);
void _Compile_Rsp_Get(void);
void _Compile_Rsp_Fetch(void);
void _Compile_Rsp_From(void);
void _Compile_Rsp_Store(void);
Word *_CfrTil_VariableGet(Namespace *ns, byte *name);
int32 _CfrTil_VariableValueGet(byte *nameSpace, byte *name);
void _Compile_SetAtAddress_WithReg(int *address, int32 reg, int32 thruReg);
void _Compile_Move_Literal_Immediate_To_Reg(int32 reg, int32 value);
void _Compile_LocalOrStackVar_RValue_To_Reg(Word *word, int32 reg);
void Do_ObjectOffset(Word *word, int32 reg);
void _Compile_GetVarLitObj_RValue_To_Reg(Word *word, int32 reg);
void _Compile_SetVarLitObj_With_Reg(Word *word, int32 reg, int32 thruReg);
void _Compile_GetVarLitObj_LValue_To_Reg(Word *word, int32 reg);
/* basis/compiler/memory.c */
void _Compile_Set_C_LValue_WithImm_ThruReg(int32 address, int32 value, int32 reg);
void _Compile_Get_C_Value_ToReg(int32 reg, int32 value);
void _Compile_Get_FromCAddress_ToReg_ThruReg(int32 reg, byte *address, int32 thruReg);
void _Compile_Get_FromCAddress_ToReg(int32 reg, byte *address);
void _Compile_Set_CAddress_WithRegValue_ThruReg(byte *address, int32 reg, int32 thruReg);
void Compile_Peek(Compiler *compiler, int32 stackReg);
void Compile_Store(Compiler *compiler, int32 stackReg);
void Compile_Poke(Compiler *compiler, int32 stackReg);
void Compile_AtEqual(int32 stackReg);
/* basis/compiler/combinators.c */
void CfrTil_EndCombinator(int32 quotesUsed, int32 moveFlag);
void CfrTil_BeginCombinator(int32 quotesUsed);
void CfrTil_DropBlock(void);
void CfrTil_BlockRun(void);
void CfrTil_LoopCombinator(void);
int32 CfrTil_WhileCombinator(void);
int32 CfrTil_DoWhileCombinator(void);
void CfrTil_If1Combinator(void);
void CfrTil_If2Combinator(void);
void CfrTil_TrueFalseCombinator2(void);
void CfrTil_TrueFalseCombinator3(void);
void CfrTil_IfElseCombinator(void);
void CfrTil_DoWhileDoCombinator(void);
void CfrTil_ForCombinator(void);
/* basis/compiler/math.c */
void Compile_Minus(Compiler *compiler);
void Compile_Plus(Compiler *compiler);
void Compile_IMultiply(Compiler *compiler);
void _Compile_Divide(Compiler *compiler, uint32 type);
void Compile_Divide(Compiler *compiler);
void Compile_Mod(Compiler *compiler);
void Compile_Group1_X_OpEqual(Compiler *compiler, int32 op);
void Compile_MultiplyEqual(Compiler *compiler);
void Compile_DivideEqual(Compiler *compiler);
void _CfrTil_Do_IncDec(int32 op);
/* basis/compiler/cpu.c */
void _CpuState_Show(Cpu *cpu);
void _Compile_CpuState_Save(Cpu *cpu);
void _Compile_CpuState_Restore(Cpu *cpu);
void Compile_CpuState_Restore(Cpu *cpu);
Cpu *_CpuState_Copy(Cpu *dst, Cpu *src);
Cpu *CpuState_Copy(Cpu *cpu0, uint32 type);
Cpu *CpuState_New(uint32 type);
Cpu *_CpuState_Save(void);
void _CpuState_Restore(Cpu *cpu);
void CpuState_Save(void);
void CpuState_Restore(void);
/* basis/compiler/stack.c */
void _Compile_Stack_Drop(int32 stackReg);
void _Compile_Stack_DropN(int32 stackReg, int n);
void _Compile_DropN_ESP(int n);
void _Compile_SetStackN_WithObject(int32 stackReg, int32 n, int32 obj);
void _Compile_Stack_Push(int32 stackReg, int32 obj);
void _Compile_Move_StackN_To_Reg(int32 reg, int32 stackReg, int32 index);
void _Compile_Move_Reg_To_StackN(int32 stackReg, int32 index, int32 reg);
void _Compile_Move_StackNRm_To_Reg(int32 reg, int32 stackReg, int32 index);
void _Compile_Move_Reg_To_StackNRm_UsingReg(int32 stackReg, int32 index, int32 reg, int32 ureg);
void _Compile_Stack_PushReg(int32 stackReg, int32 reg);
void _Compile_Stack_PopToReg(int32 stackReg, int32 reg);
void Compile_Stack_PushEAX(int32 stackReg);
void Compile_Move_TOS_To_EAX(int32 stackReg);
void Compile_Move_EAX_To_TOS(int32 stackReg);
void Compile_Pop_To_EAX(int32 stackReg);
void Compile_Pop_ToEAX_AndCall(int32 stackReg);
void Compile_MoveImm_To_TOS(int32 stackReg, int32 imm, int32 size);
void _Compile_Stack_Dup(int32 stackReg);
void _Compile_Stack_Pick(int32 stackReg);
void _Compile_Stack_Swap(int32 stackReg);
void Compile_DataStack_PushEAX(void);
void _Compile_Esp_Push(int32 value);
void Compile_DspPop_EspPush(void);
/* basis/compiler/sequence.c */
/* basis/compiler/logic.c */
void CfrTil_If(void);
void CfrTil_Else(void);
void CfrTil_EndIf(void);
void Compile_Cmp_Set_tttn_Logic(Compiler *compiler, int32 ttt, int32 negateFlag);
BlockInfo *_Compiler_Setup_BI_tttn(Compiler *compiler, int32 ttt, int32 negFlag, int32 overWriteSize);
void _Compile_SETcc(int32 ttt, int32 negFlag, int32 reg);
void _Compile_SET_tttn_REG(int32 ttt, int32 negFlag, int32 reg);
void Compile_GetLogicFromTOS(BlockInfo *bi);
int32 Compile_CheckReConfigureLogicInBlock(BlockInfo *bi, int32 overwriteFlag);
void _Compile_LogicResult(int32 reg);
void _Compile_LogicalAnd(Compiler *compiler);
void Compile_LogicalAnd(Compiler *compiler);
void Compile_LogicalNot(Compiler *compiler);
void _Compile_LogicalNot(Compiler *compiler);
void Compile_Equals(Compiler *compiler);
void Compile_DoesNotEqual(Compiler *compiler);
void Compile_LessThan(Compiler *compiler);
void Compile_GreaterThan(Compiler *compiler);
void Compile_LessThanOrEqual(Compiler *compiler);
void Compile_GreaterThanOrEqual(Compiler *compiler);
void Compile_Logical_X(Compiler *compiler, int32 op);
/* basis/core/dataObjectRun.c */
void _Namespace_Do_C_Type(Namespace *ns);
void _CfrTil_Do_ClassField(Word *word);
void CfrTil_Dot(void);
void _Word_CompileAndRecord_PushReg(Word *word, int32 reg);
void _Do_Literal(int32 value);
void _Namespace_DoNamespace(Namespace *ns, int32 immFlag);
void _CfrTil_Do_DynamicObject(DObject *dobject);
void _Do_Variable(Word *word);
void _CfrTil_Do_Literal(Word *word);
void _CfrTil_Do_LispSymbol(Word *word);
void _CfrTil_Do_Variable(Word *word);
void _Do_LocalObject_AllocateInit(Namespace *typeNamespace, byte **value, int32 size);
void _DataObject_Run(Word *word);
void DataObject_Run(void);
/* basis/core/conditionals.c */
CaseNode *_CaseNode_New(uint32 type, block block, int32 value);
void _CfrTil_Case(uint32 allocType);
void CfrTil_Case(void);
void Switch_MapFunction(dlnode *node, uint32 switchValue);
void SwitchAccessFunction(void);
void CfrTil_Switch(void);
/* basis/compiler/blocks.c */
void Byte_PtrCall(byte *ptr);
void _Block_Eval(block block);
void _Block_Copy(byte *srcAddress, int32 bsize);
void Block_Copy(byte *dst, byte *src, int32 qsize);
int32 Block_Compile_WithLogicFlag(byte *srcAddress, int32 bindex, int32 jccFlag, int negFlag);
int32 Block_Compile(byte *srcAddress, int32 bindex, int32 jccFlag);
void BlockInfo_Set_tttn(BlockInfo *bi, int32 ttt, int32 n, int32 overWriteSize);
void CfrTil_TurnOffBlockCompiler(void);
void CfrTil_TurnOnBlockCompiler(void);
BlockInfo *_CfrTil_BeginBlock0(void);
BlockInfo *_CfrTil_BeginBlock1(BlockInfo *bi);
BlockInfo *_CfrTil_BeginBlock2(BlockInfo *bi);
void CfrTil_BeginBlock(void);
Boolean _Compiler_IsFrameNecessary(Compiler *compiler);
void _CfrTil_EndBlock1(BlockInfo *bi);
byte *_CfrTil_EndBlock2(BlockInfo *bi);
byte *_CfrTil_EndBlock(void);
void CfrTil_EndBlock(void);
/* basis/core/compile.c */
void _Compile_C_Call_1_Arg(byte *function, int32 arg);
void _CompileN(byte *data, int32 size);
void _CompileFromUptoRET(byte *data);
void _Compile_WordInline(Word *word);
void _CompileFromName(byte *wordName);
void _CompileFromName_Inline(byte *wordName);
void _MoveGotoPoint(dlnode *node, int32 srcAddress, int32 key, int32 dstAddress);
void _GotoInfo_SetAndDelete(GotoInfo *gotoInfo, byte *address);
void _InstallGotoPoint_Key(dlnode *node, int32 bi, int32 key);
void _CheckForGotoPoint(dlnode *node, int32 key, int32 *status);
void _RemoveGotoPoint(dlnode *node, int32 key, int32 *status);
void _CfrTil_InstallGotoCallPoints_Keyed(BlockInfo *bi, int32 key);
int32 _CfrTil_MoveGotoPoint(int32 srcAddress, int32 key, int32 dstAddress);
int32 CfrTil_CheckForGotoPoints(int32 key);
int32 CfrTil_RemoveGotoPoints(int32 key);
/* basis/core/_system.c */
void _System_TimerInit(System *system, int32 i);
void _System_Time(System *system, uint timer, char *format, byte *toString);
void System_Time(System *system, uint timer, char *string, int tflag);
void System_InitTime(System *system);
void System_RunInit(System *system);
void _System_Copy(System *system, System *system0, uint32 type);
System *System_Copy(System *system0, uint32 type);
void _System_Init(System *system);
void System_Init(System *system);
System *System_New(uint32 type);
/* basis/compiler/optimize.c */
void _GetRmDispImm(CompileOptimizeInfo *optInfo, Word *word, int32 suggestedReg);
void PeepHole_Optimize(void);
int32 _GetWordStackListState(int count);
int32 _CheckOptimizeOperands(Compiler *compiler, int32 maxOperands);
int32 CheckOptimize(Compiler *compiler, int32 maxOperands);
/* basis/compiler/bits.c */
void Compile_X_Group3(Compiler *compiler, int32 code);
void Compile_X_Shift(Compiler *compiler, int32 op, int32 stackFlag);
void Compile_BitWise_NOT(Compiler *compiler);
void Compile_BitWise_NEG(Compiler *compiler);
void Compile_ShiftLeft(void);
void Compile_ShiftRight(void);
/* basis/compiler/udis.c */
void _Udis_PrintInstruction(ud_t *ud, byte *address, byte *prefix, byte *postfix);
int32 _Udis_GetInstructionSize(ud_t *ud, byte *address);
ud_t *_Udis_Init(ud_t *ud);
int32 _Debugger_Udis_OneInstruction(Debugger *debugger, byte *address, byte *prefix, byte *postfix);
void _Udis_Disassemble(ud_t *ud, byte *address, int32 number, int32 cflag);
/* basis/compiler/arrays.c */
int32 _CheckArrayDimensionForVariables_And_UpdateCompilerState(void);
void Compile_ArrayDimensionOffset(Word *word, int32 dimSize, int32 objSize);
int32 Do_NextArrayWordToken(Word *word, byte *token, Word *arrayBaseObject, int32 objSize, int32 saveCompileMode, int32 *variableFlag);
void CfrTil_ArrayBegin(void);
void CfrTil_ArrayEnd(void);
/* basis/core/io.c */
int32 GetTerminalWidth(void);
char kbhit(void);
int _Key(FILE *f);
int Key_Kbhit(FILE *f);
int Key(void);
byte _CfrTil_Key(ReadLiner *rl);
void Emit(byte c);
void Context_DoPrompt(Context *cntx);
void CfrTil_DoPrompt(void);
void _Printf(byte *format, ...);
/* basis/core/symbol.c */
void _Symbol_NameInit(Symbol *symbol, byte *name);
void _Symbol_Init_AllocName(Symbol *symbol, byte *name, uint32 allocType);
Symbol *__Symbol_New(uint32 allocType);
Symbol *_Symbol_New(byte *name, uint32 allocType);
Symbol *Symbol_New(byte *name);
Symbol *Symbol_NewValue(int32 value, uint32 allocType);
Symbol *_Symbol_CompareName(Symbol *symbol, byte *name);
Symbol *Symbol_CompareName(Symbol *symbol, byte *name);
/* basis/repl.c */
void _Repl(block repl);
/* basis/core/syntax.c */
int32 _Interpret_CheckEqualBeforeSemi_LValue(byte *nc);
int32 Interpret_CheckEqualBeforeSemi_LValue(Word *word);
void Interpret_DoParenthesizedRValue(void);
int32 _Interpret_Do_CombinatorLeftParen(void);
void CfrTil_C_LeftParen(void);
void CfrTil_InterpretNBlocks(int blocks, int takesLParenAsBlockFlag);
/* basis/core/dataObjectNew.c */
byte *_CfrTil_NamelessObjectNew(int32 size, int32 allocType);
byte *CfrTil_NamelessObjectNew(int32 size);
void _Class_Object_Init(byte *obj, Namespace *ns);
Word *_Class_Object_New(byte *name, uint64 category);
Namespace *_Class_New(byte *name, uint64 type, int32 cloneFlag);
Word *_CfrTil_ClassField_New(byte *token, Class *aclass, int32 size, int32 offset);
Word *_CfrTil_Variable_New(byte *name, int32 value);
void _CfrTil_Label(byte *lname);
Word *_CfrTil_LocalWord(byte *name, int32 index, int64 ctype, uint64 ltype);
Word *Literal_New(Lexer *lexer, uint32 uliteral);
Namespace *_Namespace_New(byte *name, Namespace *containingNs);
Word *_DataObject_New(uint64 type, Word *word, byte *name, uint64 ctype, uint64 ltype, int32 index, int32 value, int32 startCharRlIndex);
void _CfrTil_MachineCodePrimitive_NewAdd(const char *name, uint64 cType, block *callHook, byte *function, int32 functionArg, const char *nameSpace, const char *superNamespace);
/* basis/cfrtil.c */
void _CfrTil_Run(CfrTil *cfrTil, int32 restartCondition);
void _CfrTil_ReStart(CfrTil *cfrTil, int32 restartCondition);
void _CfrTil_CpuState_Show(void);
void CfrTil_CpuState_Show(void);
void CfrTil_Debugger_State_Show(void);
void _CfrTil_NamespacesInit(CfrTil *cfrTil);
void _CfrTil_DataStack_Init(CfrTil *cfrTil);
void CfrTil_DataStack_Init(void);
void _CfrTil_Init(CfrTil *cfrTil, Namespace *nss);
void CfrTil_ResetMemory(CfrTil *cfrTil);
CfrTil *_CfrTil_New(CfrTil *cfrTil);
void CfrTil_Lexer_SourceCodeOn(void);
void _CfrTil_AddStringToSourceCode(CfrTil *cfrtil, byte *str);
void CfrTil_AddStringToSourceCode(CfrTil *cfrtil, byte *str);
void _CfrTil_SC_ScratchPadIndex_Init(CfrTil *cfrtil);
void __CfrTil_SourceCode_Init(CfrTil *cfrtil);
void _CfrTil_SourceCode_Init(CfrTil *cfrtil);
void _CfrTil_InitSourceCode(CfrTil *cfrtil);
void CfrTil_InitSourceCode(CfrTil *cfrtil);
void _CfrTil_InitSourceCode_WithName(CfrTil *cfrtil, byte *name);
void CfrTil_InitSourceCode_WithCurrentInputChar(CfrTil *cfrtil);
void CfrTil_SourceCode_Init(void);
void _CfrTil_DebugSourceCodeCompileOn(void);
void _CfrTil_DebugSourceCodeCompileOff(void);
void CfrTil_SourceCodeCompileOn(void);
void _CfrTil_FinishSourceCode(CfrTil *cfrtil, Word *word);
void _CfrTil_UnAppendFromSourceCode(CfrTil *cfrtil, int nchars);
void _CfrTil_UnAppendTokenFromSourceCode(CfrTil *cfrtil, byte *tkn);
void _CfrTil_AppendCharToSourceCode(CfrTil *cfrtil, byte c);
void CfrTil_AppendCharToSourceCode(CfrTil *cfrtil, byte c, int32 convertToSpaceFlag);
byte *_CfrTil_GetTokenFromTokenList(Lexer *lexer);
void _CfrTil_AddTokenToTailOfTokenList(byte *token);
void _CfrTil_AddTokenToHeadOfTokenList(byte *token);
void CfrTil_ClearTokenList(void);
void CfrTil_OptimizeOn(void);
void CfrTil_OptimizeOff(void);
void CfrTil_StringMacrosOn(void);
void CfrTil_StringMacrosOff(void);
void CfrTil_InlineOn(void);
void CfrTil_InlineOff(void);
void _CfrTil_DebugOff(void);
void _CfrTil_DebugOn(void);
/* basis/core/parse.c */
void _CfrTil_Parse_ClassStructure(int32 cloneFlag);
void Compile_InitRegisterParamenterVariables(Compiler *compiler);
void Compiler_LocalObjectInit(Namespace *typeNamespace, Word *word);
Namespace *_CfrTil_Parse_LocalsAndStackVariables(int32 svf, int32 lispMode, ListObject *args, int32 forceNewLocalsFlag);
void Lexer_ParseAsAString(Lexer *lexer);
void _Lexer_ParseBinary(Lexer *lexer, int offset);
void Lexer_ParseBinary(Lexer *lexer, byte *token, int32 offset);
void Lexer_ParseBigNum(Lexer *lexer, byte *token);
void _Lexer_ParseHex(Lexer *lexer, byte *token);
void _Lexer_ParseDecimal(Lexer *lexer, byte *token);
void Lexer_ParseObject(Lexer *lexer, byte *token);
byte *Parse_Macro(int64 type);
/* basis/memSpace.c */
byte *_mmap_AllocMem(int32 size);
void mmap_FreeMem(byte *chunk, int32 size);
byte *mmap_AllocMem(int32 size);
void MemChunk_Show(MemChunk *mchunk);
void _MemChunk_WithSymbol_Show(MemChunk *mchunk, int32 flag);
void _MemChunk_Account(MemChunk *mchunk, int32 flag);
void _Mem_ChunkFree(MemChunk *mchunk);
byte *_Mem_ChunkAllocate(int32 size, uint32 allocType);
byte *Mem_Allocate(int32 size, uint32 allocType);
void Mem_FreeItem(dllist *mList, byte *item);
void FreeChunkList(dllist *list);
void FreeNba_BaNode(NamedByteArray *nba, dlnode *node);
void FreeNba_BaList(NamedByteArray *nba);
void NBA_FreeChunkType(Symbol *s, uint32 allocType, int32 exactFlag);
NamedByteArray *MemorySpace_NBA_New(MemorySpace *memSpace, byte *name, int32 size, int32 allocType);
void MemorySpace_Init(MemorySpace *ms);
MemorySpace *MemorySpace_New(void);
NamedByteArray *_OVT_Find_NBA(byte *name);
void OVT_MemList_FreeNBAMemory(byte *name, uint32 moreThan, int32 always);
void OVT_MemListFree_ContextMemory(void);
void OVT_MemListFree_TempObjects(void);
void OVT_MemListFree_CompilerTempObjects(void);
void OVT_MemListFree_LispTemp(void);
void OVT_MemListFree_Session(void);
void OVT_MemListFree_Buffers(void);
void OVT_MemListFree_HistorySpace(void);
void _OVT_MemListFree_CfrTilInternal(void);
void _MemList_FreeExactType(dllist *list, int allocType);
void _MemList_FreeVariousTypes(dllist *list, int allocType);
void NBAsMemList_FreeExactType(int allocType);
void NBAsMemList_FreeVariousTypes(int allocType);
void NBA_Show(NamedByteArray *nba, int32 flag);
/* basis/init.c */
void _CfrTil_Init_SessionCore(CfrTil *cfrTil, int32 cntxDelFlag, int32 promptFlag);
void CfrTil_ContextInit(void);
void CfrTil_ResetAll_Init(CfrTil *cfrTil);
void _CfrTil_InitialAddWordToNamespace(Word *word, byte *containingNamespaceName, byte *superNamespaceName);
void _CfrTil_CPrimitiveNewAdd(const char *name, block b, uint64 ctype, uint64 ltype, const char *nameSpace, const char *superNamespace);
void CfrTil_AddCPrimitives(void);
void CfrTil_MachineCodePrimitive_AddWords(void);
/* basis/system.c */
void *_dlsym(byte *sym, byte *lib);
void *_Dlsym(byte *sym, byte *lib);
void Dlsym(byte *sym, byte *lib);
void CfrTil_Dlsym(void);
void CfrTil_system0(void);
void CfrTil_system1(void);
void CfrTil_system2(void);
void CfrTil_system3(void);
byte *_CfrTil_GetSystemState_String0(byte *buf);
byte *_CfrTil_GetSystemState_String1(byte *buf);
void _CfrTil_SystemState_Print(int32 pflag);
void __CfrTil_Dump(int32 address, int32 number, int32 dumpMod);
void _CfrTil_Source(Word *word, int32 addToHistoryFlag);
void _CfrTil_Dump(int32 dumpMod);
/* basis/core/charSet.c */
Boolean CharTable_IsCharType(byte c, uint32 type);
int32 CharSet_IsDelimiter(CharSet *cset, byte ch);
void CharSet_SetChar(CharSet *cset, byte ch);
void CharSet_UnSetChar(CharSet *cset, byte ch);
CharSet *CharSet_Init(CharSet *cset, int32 size, byte *initString);
CharSet *CharSet_Allocate(int32 size, uint32 allocType);
CharSet *_CharSet_New(byte *initString, int32 size, uint32 allocType);
CharSet *CharSet_New(byte *initString, uint32 allocType);
/* basis/core/dllist.c */
void _dlnode_Init(dlnode *node);
dlnode *_dlnode_New(uint32 allocType);
dlnode *dlnode_Next(dlnode *node);
dlnode *dlnode_Previous(dlnode *node);
void dlnode_InsertThisAfterANode(dlnode *node, dlnode *anode);
void dlnode_InsertThisBeforeANode(dlnode *node, dlnode *anode);
dlnode *dlnode_Remove(dlnode *node);
void dlnode_ReplaceNodeWithANode(dlnode *node, dlnode *anode);
void dlnode_Replace(dlnode *replacedNode, dlnode *replacingNode);
void _dllist_Init(dllist *list);
void dllist_Init(dllist *list, dlnode *n_After, dlnode *n_Before);
dllist *_dllist_New(uint32 allocType);
dllist *dllist_New(void);
void dllist_ReInit(dllist *list);
int32 dllist_Length(dllist *list);
void _dllist_AddNodeToHead(dllist *list, dlnode *node);
void dllist_AddNodeToHead(dllist *list, dlnode *node);
void dllist_AddNodeToTail(dllist *list, dlnode *node);
dlnode *dllist_Head(dllist *list);
dlnode *dllist_Tail(dllist *list);
dlnode *_dllist_First(dllist *list);
dlnode *dllist_First(dllist *list);
dlnode *_dllist_Last(dllist *list);
dlnode *dllist_Last(dllist *list);
dlnode *dllist_NodePrevious(dllist *list, dlnode *node);
dlnode *dllist_NodeNext(dllist *list, dlnode *node);
dlnode *_dllist_Before(dllist *list);
dlnode *dllist_SetCurrentNode_Before(dllist *list);
dlnode *_dllist_After(dllist *list);
dlnode *dllist_SetCurrentNode_After(dllist *list);
dlnode *_dllist_AddNamedValue(dllist *list, byte *name, int32 value, uint32 allocType);
dobject *_dllist_Push_M_Slot_Node(dllist *list, int32 dobjType, int32 allocType, int m_slots, ...);
dlnode *_dllist_PopNode(dllist *list);
void _dllist_DropN(dllist *list, int32 n);
int32 _dllist_Get_N_Node_M_Slot(dllist *list, int32 n, int32 m);
void _dllist_Set_N_Node_M_Slot(dllist *list, int32 n, int32 m, int32 value);
int _dllist_Depth(dllist *list);
int32 _dllist_GetTopValue(dllist *list);
int32 _dllist_SetTopValue(dllist *list, int32 value);
void dllist_Map(dllist *list, MapFunction0 mf);
void dllist_Map1(dllist *list, MapFunction1 mf, int32 one);
void dllist_Map2(dllist *list, MapFunction2 mf, int32 one, int32 two);
int32 dllist_Map3(dllist *list, MapFunction3 mf, int32 one, int32 two, int32 three);
void dllist_Map_OnePlusStatus(dllist *list, MapFunction2 mf, int32 one, int32 *status);
Word *_Tree_Map_0(Word *first, MapFunction mf);
Word *_TreeMap_NextWord(Word *thisWord);
void _Tree_Map_State_2(dllist *list, uint64 state, MapSymbolFunction2 mf, int32 one, int32 two);
Word *_Tree_Map_State_Flag_OneArg(Word *word, uint64 state, int32 oneNamespaceFlag, MapFunction_Cell_1 mf, int32 one);
/* basis/core/interpret.c */
Boolean _Interpreter_IsWordPrefixing(Interpreter *interp, Word *word);
Word *_Compiler_CopyDuplicatesAndPush(Compiler *compiler, Word *word);
Word *Compiler_CopyDuplicatesAndPush(Word *word);
Word *_Interpreter_DoWord_Default(Interpreter *interp, Word *word);
void _Interpreter_DoWord(Interpreter *interp, Word *word, int32 tokenStartReadLineIndex);
Word *_Interpreter_NewWord(Interpreter *interp, byte *token);
Word *_Interpreter_TokenToWord(Interpreter *interp, byte *token);
Word *Interpreter_ReadNextTokenToWord(Interpreter *interp);
Word *Interpreter_InterpretAToken(Interpreter *interp, byte *token, int32 tokenStartReadLineIndex);
void Interpreter_InterpretNextToken(Interpreter *interp);
/* basis/core/lexer.c */
void CfrTil_LexerTables_Setup(CfrTil *cfrtl);
byte Lexer_NextNonDelimiterChar(Lexer *lexer);
Word *Lexer_ObjectToken_New(Lexer *lexer, byte *token);
int32 _Lexer_EvalNonDebugToken(byte *token);
byte *_Lexer_NextNonDebugTokenWord(Lexer *lexer);
byte *Lexer_PeekNextNonDebugTokenWord(Lexer *lexer);
void _Lexer_GetChar(Lexer *lexer, byte c);
void Lexer_GetChar(Lexer *lexer);
byte *_Lexer_LexNextToken_WithDelimiters(Lexer *lexer, byte *delimiters, int32 checkListFlag, uint64 state);
void Lexer_LexNextToken_WithDelimiters(Lexer *lexer, byte *delimiters);
byte *_Lexer_ReadToken(Lexer *lexer, byte *delimiters);
byte *Lexer_ReadToken(Lexer *lexer);
void __Lexer_AppendCharacterToTokenBuffer(Lexer *lexer, byte c);
void _Lexer_AppendCharacterToTokenBuffer(Lexer *lexer);
void Lexer_Append_ConvertedCharacterToTokenBuffer(Lexer *lexer);
void Lexer_AppendCharacterToTokenBuffer(Lexer *lexer);
byte Lexer_UnAppendCharacterToTokenBuffer(Lexer *lexer);
byte Lexer_LastChar(Lexer *lexer);
void Lexer_SetTokenDelimiters(Lexer *lexer, byte *delimiters, uint32 allocType);
void Lexer_SetBasicTokenDelimiters(Lexer *lexer, byte *delimiters, uint32 allocType);
void Lexer_Init(Lexer *lexer, byte *delimiters, uint64 state, uint32 allocType);
Lexer *Lexer_New(uint32 allocType);
void _Lexer_Copy(Lexer *lexer, Lexer *lexer0, uint32 allocType);
Lexer *Lexer_Copy(Lexer *lexer0, uint32 allocType);
void Lexer_RestartToken(Lexer *lexer);
void Lexer_SourceCodeOn(Lexer *lexer);
void Lexer_SourceCodeOff(Lexer *lexer);
void _Lexer_AppendCharToSourceCode(Lexer *lexer, byte c, int32 convert);
void Lexer_DoDelimiter(Lexer *lexer);
Boolean Lexer_IsCurrentInputCharADelimiter(Lexer *lexer);
void Lexer_Default(Lexer *lexer);
void Lexer_MakeItTheNextToken(Lexer *lexer);
void TerminatingMacro(Lexer *lexer);
void NonTerminatingMacro(Lexer *lexer);
int32 _Lexer_MacroChar_NamespaceCheck(Lexer *lexer, byte *nameSpace);
void Lexer_FinishTokenHere(Lexer *lexer);
void SingleEscape(Lexer *lexer);
void _MultipleEscape(Lexer *lexer);
void DoubleQuote(Lexer *lexer);
void Minus(Lexer *lexer);
void ForwardSlash(Lexer *lexer);
void Star(Lexer *lexer);
void AddressOf(Lexer *lexer);
void AtFetch(Lexer *lexer);
void Semi(Lexer *lexer);
void GreaterThan(Lexer *lexer);
void Dot(Lexer *lexer);
void Lexer_DoReplMacro(Lexer *lexer);
void Lexer_CheckMacroRepl(Lexer *lexer);
void Comma(Lexer *lexer);
void _BackSlash(Lexer *lexer, int32 flag);
void BackSlash(Lexer *lexer);
void CarriageReturn(Lexer *lexer);
void NewLine(Lexer *lexer);
void _EOF(Lexer *lexer);
void _Zero(Lexer *lexer);
int32 Lexer_CheckIfDone(Lexer *lexer, int32 flags);
byte _Lexer_NextChar(ReadLiner *rl);
void Lexer_SetInputFunction(Lexer *lexer, byte (*lipf)(ReadLiner *));
void Lexer_DoChar(Lexer *lexer, byte c);
Boolean Lexer_IsTokenQualifiedID(Lexer *lexer);
Boolean Lexer_IsTokenReverseDotted(Lexer *lexer);
Boolean Lexer_IsTokenForwardDotted(Lexer *lexer);
/* basis/core/cstack.c */
void Stack_Print_AValue_WordName(Stack *stack, int i, byte *stackName, byte *buffer);
void Stack_Print_AValue(uint32 *stackPointer, int i, byte *stackName, byte *buffer);
void _Stack_PrintHeader(Stack *stack, byte *name);
void _Stack_PrintValues(byte *name, uint32 *stackPointer, int depth);
void Stack_PrintValues(byte *name, Stack *stack, int depth);
void _Stack_Print(Stack *stack, byte *name);
int32 _Stack_Overflow(Stack *stack);
int32 _Stack_IsEmpty(Stack *stack);
void _Stack_Push(Stack *stack, int32 value);
void _Stack_Dup(Stack *stack);
int32 __Stack_Pop(Stack *stack);
int32 _Stack_Pop_ExceptionFlag(Stack *stack, int32 exceptionOnEmptyFlag);
int32 _Stack_Pop(Stack *stack);
int32 _Stack_PopOrTop(Stack *stack);
int32 _Stack_DropN(Stack *stack, int32 n);
int32 _Stack_Top(Stack *stack);
int32 _Stack_Pick(Stack *stack, int32 offset);
int32 _Stack_PickFromBottom(Stack *stack, int32 offset);
int32 _Stack_Bottom(Stack *stack);
void _Stack_SetBottom(Stack *stack, int32 value);
void _Stack_SetTop(Stack *stack, int32 value);
int32 _Stack_NOS(Stack *stack);
void _Stack_Drop(Stack *stack);
void Stack_Push(Stack *stack, int32 value);
int32 Stack_Pop_WithExceptionOnEmpty(Stack *stack);
int32 Stack_Pop_WithZeroOnEmpty(Stack *stack);
void Stack_Dup(Stack *stack);
int32 _Stack_IntegrityCheck(Stack *stack);
int32 _Stack_Depth(Stack *stack);
int32 Stack_Depth(Stack *stack);
void Stack_SetStackMax(Stack *stack, int32 value);
void _Stack_Init(Stack *stack, int32 slots);
void Stack_Delete(Stack *stack);
void Stack_Init(Stack *stack);
Stack *Stack_New(int32 slots, uint32 type);
Stack *Stack_Copy(Stack *stack, uint32 type);
void _PrintNStackWindow(uint32 *reg, byte *name, byte *regName, int32 size);
void _CfrTil_PrintNReturnStack(int32 size);
void _CfrTil_PrintNDataStack(int32 size);
/* basis/core/classes.c */
void CfrTil_ClassStructureEnd(void);
void CfrTil_ClassStructureBegin(void);
void CfrTil_CloneStructureBegin(void);
/* basis/debugOutput.c */
void Debugger_Menu(Debugger *debugger);
void Debugger_Locals_ShowALocal(Debugger *debugger, Word *localsWord, byte *buffer);
void Debugger_Locals_Show(Debugger *debugger);
int32 Debugger_TerminalLineWidth(Debugger *debugger);
void Debugger_ShowStackChange(Debugger *debugger, Word *word, byte *insert, byte *achange);
void Debugger_ShowEffects(Debugger *debugger, int32 stepFlag);
char *_String_HighlightTokenInputLine(byte *cc_line, byte *token, int32 tokenStart, int32 border, int32 flag);
byte *Debugger_ShowSourceCodeLine(Debugger *debugger, Word *word, byte *token0, int32 prevLength);
void _CfrTil_ShowInfo(Debugger *debugger, byte *prompt, int32 signal, int32 force);
void Debugger_ShowInfo(Debugger *debugger, byte *prompt, int32 signal);
void Debugger_ShowState(Debugger *debugger, byte *prompt);
void Debugger_ConsiderAndShowWord(Debugger *debugger);
void _Debugger_DoNewlinePrompt(Debugger *debugger);
void _Debugger_DoState(Debugger *debugger);
void _Debug_ExtraShow(int32 showStackFlag, int32 verbosity, int32 wordList, byte *format, ...);
/* basis/core/namespace.c */
void _Namespace_SetAsInNamespace(Namespace *ns);
void _Namespace_ResetFromInNamespace(Namespace *ns);
void _Namespace_DoAddSymbol(Namespace *ns, Symbol *symbol);
void Namespace_DoAddSymbol(Namespace *ns, Symbol *symbol);
void _Namespace_DoAddWord(Namespace *ns, Word *word);
void _Namespace_AddToNamespacesHead(Namespace *ns);
void _Namespace_AddToNamespacesHead_SetAsInNamespace(Namespace *ns);
void _Namespace_AddToNamespacesTail(Namespace *ns);
void _Namespace_AddToNamespacesTail_ResetFromInNamespace(Namespace *ns);
Namespace *_Namespace_IsUsing(Namespace *ns);
Namespace *Namespace_IsUsing(byte *name);
void _Namespace_SetState(Namespace *ns, uint64 state);
Word *_Namespace_FirstOnUsingList(void);
void _Namespace_AddToUsingList(Namespace *ns);
void _Namespace_ActivateAsPrimary(Namespace *ns);
void Namespace_ActivateAsPrimary(byte *name);
void Namespace_MoveToTail(byte *name);
void Namespace_SetAsNotUsing(byte *name);
void _Namespace_SetAsNotUsing_MoveToTail(Namespace *ns);
void Namespace_SetAsNotUsing_MoveToTail(byte *name);
int32 _Namespace_VariableValueGet(Namespace *ns, byte *name);
void _Namespace_VariableValueSet(Namespace *ns, byte *name, int32 value);
Namespace *_CfrTil_Namespace_InNamespaceSet(Namespace *ns);
Namespace *CfrTil_Namespace_InNamespaceSet(byte *name);
Namespace *_CfrTil_Namespace_InNamespaceGet(void);
Namespace *_CfrTil_InNamespace(void);
Boolean _CfrTil_IsContainingNamespace(byte *wordName, byte *namespaceName);
void Namespace_DoNamespace(byte *name);
void Symbol_NamespacePrettyPrint(Symbol *symbol, int32 indentFlag, int32 indentLevel);
Namespace *_Namespace_Find(byte *name, Namespace *superNamespace, int32 exceptionFlag);
Namespace *Namespace_Find(byte *name);
void _Namespace_UsingLast(byte *name);
void _Namespace_RemoveFromUsingList(Namespace *ns);
void Namespace_RemoveFromUsingList(byte *name);
void _RemoveSubNamespacesFromUsingList(Symbol *symbol, Namespace *ns);
void Namespace_MoveToFirstOnUsingList(byte *name);
void Namespace_RemoveFromUsingList_WithCheck(byte *name);
void _Namespace_Clear(Namespace *ns);
void Namespace_Clear(byte *name);
Namespace *Namespace_FindOrNew_SetUsing(byte *name, Namespace *containingNs, int32 setUsingFlag);
Namespace *Namespace_FindOrNew_Local(void);
void _Namespace_PrintWords(Namespace *ns);
void _Namespace_MapAny_2Args(MapSymbolFunction2 msf2, int32 one, int32 two);
void _Namespace_MapUsing_2Args(MapSymbolFunction2 msf2, int32 one, int32 two);
/* basis/history.c */
HistoryStringNode *HistoryStringNode_New(byte *hstring);
HistoryStringNode *HistorySymbolList_Find(byte *hstring);
void ReadLine_ShowHistoryNode(ReadLiner *rl);
void _OpenVmTil_AddStringToHistoryList(byte *istring);
void OpenVmTil_AddStringToHistory(void);
void OpenVmTil_AddStringToHistoryOn(void);
void OpenVmTil_AddStringToHistoryOff(void);
void HistorySpace_Delete(void);
HistorySpace *_HistorySpace_Init(OpenVmTil *ovt, int32 reset);
void _HistorySpace_New(OpenVmTil *ovt, int32 resetFlag);
void HistorySpace_Reset(void);
/* basis/core/readline.c */
void _ReadLine_NullDelimitInputBuffer(ReadLiner *rl);
void _ReadLine_QuickAppendCharacter(ReadLiner *rl, byte chr);
void _ReadLine_SetOutputLineCharacterNumber(ReadLiner *rl);
void __ReadLine_AppendCharacter(ReadLiner *rl, byte chr);
void __ReadLine_AppendCharacter_Actual(ReadLiner *rl, byte chr);
void _ReadLine_AppendCharacter(ReadLiner *rl);
void _ReadLine_AppendCharacter_Actual(ReadLiner *rl);
void ReadLine_DoCursorMoveInput(ReadLiner *rl, int32 newCursorPosition);
void ReadLine_SetCursorPosition(ReadLiner *rl, int32 pos);
void ReadLiner_CommentToEndOfLine(ReadLiner *rl);
int32 ReadLiner_PeekSkipSpaces(ReadLiner *rl);
void ReadLiner_Done(ReadLiner *rl);
Boolean ReadLiner_IsDone(ReadLiner *rl);
void _ReadLine_MoveInputStartToLineStart(int32 fromPosition);
void _ReadLine_PrintfClearTerminalLine(void);
void ReadLine_ClearCurrentTerminalLine(ReadLiner *rl, int32 fromPosition);
void ReadLine_SetInputLine(ReadLiner *rl, byte *buffer);
void ReadLine_InputLine_Clear(ReadLiner *rl);
void ReadLine_InputLine_Init(ReadLiner *rl);
void ReadLine_RunInit(ReadLiner *rl);
void ReadLine_Init(ReadLiner *rl, ReadLiner_KeyFunction ipf);
ReadLiner *ReadLine_New(uint32 type);
void _ReadLine_Copy(ReadLiner *rl, ReadLiner *rl0, uint32 type);
ReadLiner *ReadLine_Copy(ReadLiner *rl0, uint32 type);
void ReadLine_TabWordCompletion(ReadLiner *rl);
void __ReadLine_AppendCharacterAndCursoRight(ReadLiner *rl, byte c);
void _ReadLine_AppendCharacterAndCursoRight(ReadLiner *rl);
void _ReadLine_AppendAndShowCharacter(ReadLiner *rl, byte c);
void ReadLine_AppendAndShowCharacter(ReadLiner *rl);
byte *ReadLine_GetPrompt(ReadLiner *rl);
void ReadLine_SetPrompt(ReadLiner *rl, byte *newPrompt);
byte *ReadLine_GetAltPrompt(ReadLiner *rl);
byte *ReadLine_GetNormalPrompt(ReadLiner *rl);
void _ReadLine_Show(ReadLiner *rl, byte *prompt);
void _ReadLine_ShowLine(ReadLiner *rl, byte *prompt);
void ReadLine_ShowLine(ReadLiner *rl);
void _ReadLine_ClearAndShowLine(ReadLiner *rl, byte *prompt);
void __ReadLine_DoStringInput(ReadLiner *rl, byte *string, byte *prompt);
void ReadLine_ClearAndShowLine(ReadLiner *rl);
void _ReadLine_ShowCursor(ReadLiner *rl, byte *prompt);
void ReadLine_ShowCursor(ReadLiner *rl);
void _ReadLine_DoStringInput(ReadLiner *rl, byte *string, byte *prompt);
void ReadLine_ShowStringWithCursor(ReadLiner *rl, byte *string);
void ReadLine_ClearAndShowLineWithCursor(ReadLiner *rl);
void ReadLine_ShowNormalPrompt(ReadLiner *rl);
void ReadLine_InsertCharacter(ReadLiner *rl);
void ReadLine_SaveCharacter(ReadLiner *rl);
void _ReadLine_InsertStringIntoInputLineSlotAndShow(ReadLiner *rl, int32 startOfSlot, int32 endOfSlot, byte *data);
void ReadLiner_InsertTextMacro(ReadLiner *rl, Word *word);
void ReadLine_DeleteChar(ReadLiner *rl);
int32 ReadLine_IsLastCharADot(ReadLiner *rl, int32 pos);
int32 ReadLine_FirstCharOfToken_FromLastChar(ReadLiner *rl, int32 pos);
int32 ReadLine_IsThereADotSeparator(ReadLiner *rl, int32 pos);
int32 ReadLine_LastCharOfLastToken_FromPos(ReadLiner *rl, int32 pos);
int32 ReadLine_EndOfLastToken(ReadLiner *rl);
int32 ReadLine_BeginningOfLastToken(ReadLiner *rl);
Boolean ReadLine_IsReverseTokenQualifiedID(ReadLiner *rl);
byte _ReadLine_Key(ReadLiner *rl, byte c);
byte ReadLine_Key(ReadLiner *rl);
byte ReadLine_GetNextCharFromString(ReadLiner *rl);
void ReadLine_SetRawInputFunction(ReadLiner *rl, ReadLiner_KeyFunction ripf);
void ReadLine_ReadFileToString(ReadLiner *rl, FILE *file);
void ReadLine_SetInputString(ReadLiner *rl, byte *string);
void _ReadLine_TabCompletion_Check(ReadLiner *rl);
void _ReadLine_GetLine(ReadLiner *rl, byte c);
void ReadLine_GetLine(ReadLiner *rl);
byte ReadLine_NextChar(ReadLiner *rl);
void Readline_Setup_OneStringInterpret(ReadLiner *rl, byte *str);
void Readline_SaveInputLine(ReadLiner *rl);
void Readline_RestoreInputLine(ReadLiner *rl);
int32 _Readline_CheckArrayDimensionForVariables(ReadLiner *rl);
int32 _Readline_Is_AtEndOfBlock(ReadLiner *rl0);
/* basis/core/dataStack.c */
uint32 _DataStack_Pop(void);
void _DataStack_Push(int32 value);
void _DataStack_Dup(void);
void _DataStack_DropN(int n);
void _DataStack_Drop(void);
int32 DataStack_Overflow(void);
int32 DataStack_Underflow(void);
void DataStack_Check(void);
int32 DataStack_Depth(void);
int32 DataStack_Pop(void);
void CpuState_SyncStackPointersFromCpuState(Cpu *cpus);
void Debugger_SyncStackPointersFromCpuState(Debugger *debugger);
void _CfrTil_SetStackPointerFromDsp(CfrTil *cfrTil);
void CfrTil_SetStackPointerFromDsp(CfrTil *cfrTil);
void CfrTil_SyncStackPointers(void);
void _CfrTil_InitDspFromStackPointer(CfrTil *cfrTil);
void CfrTil_InitDspFromStackPointer(CfrTil *cfrTil);
void CfrTil_DataStack_InitEssential(CfrTil *cfrTil);
/* basis/context.c */
void _Context_Prompt(int32 control);
byte *_Context_Location(Context *cntx);
byte *Context_Location(void);
Context *_Context_New(CfrTil *cfrTil);
void _Context_Run_1(Context *cntx, ContextFunction_1 contextFunction, byte *arg);
void _Context_Run_2(Context *cntx, ContextFunction_2 contextFunction, byte *arg, int32 arg2);
void _Context_Run(Context *cntx, ContextFunction contextFunction);
Context *CfrTil_Context_PushNew(CfrTil *cfrTil);
void CfrTil_Context_PopDelete(CfrTil *cfrTil);
void _CfrTil_Contex_NewRun_1(CfrTil *cfrTil, ContextFunction_1 contextFunction, byte *arg);
void _CfrTil_Contex_NewRun_2(CfrTil *cfrTil, ContextFunction_2 contextFunction, byte *arg, int32 arg2);
void _CfrTil_Contex_NewRun_Void(CfrTil *cfrTil, Word *word);
void _Context_InterpretString(Context *cntx, byte *str);
void _CfrTil_ContextNew_InterpretString(CfrTil *cfrTil, byte *str);
void _Context_InterpretFile(Context *cntx);
void _Context_IncludeFile(Context *cntx, byte *filename, int32 interpretFlag);
void _CfrTil_ContextNew_IncludeFile(byte *filename);
int32 _Context_StrCmpNextToken(Context *cntx, byte *check);
void _Context_DoubleQuoteMacro(Context *cntx);
void Context_DoubleQuoteMacro(void);
void _Tick(Context *cntx);
void Context_Interpret(Context *cntx);
byte *Context_IsInFile(Context *cntx);
/* basis/core/word.c */
void _Word_Run(Word *word);
void Word_Run(Word *word);
void Word_Eval0(Word *word);
void _Word_Eval_Debug(Word *word);
void _Word_Eval(Word *word);
void _Word_Interpret(Word *word);
void _Word_Compile(Word *word);
Namespace *_Word_Namespace(Word *word);
Word *_Word_Allocate(uint32 allocType);
void _Word_Copy(Word *word, Word *word0);
Word *Word_Copy(Word *word0, uint32 allocType);
void _Word_Finish(Word *word);
void _Word_DefinitionStore(Word *word, block code);
void _Word_InitFinal(Word *word, byte *code);
void _Word_Add(Word *word, int32 addToInNs, Namespace *addToNs);
Word *_Word_New(byte *name, uint64 ctype, uint64 ltype, uint32 allocType);
Word *_Word_Create(byte *name, uint64 ctype, uint64 ltype, uint32 allocType);
Word *Word_Create(byte *name);
void Word_PrintOffset(Word *word, int32 increment, int32 totalIncrement);
void _Word_Location_Printf(Word *word);
byte *_Word_SourceCodeLocation_pbyte(Word *word);
void Word_PrintName(Word *word);
void _Word_Print(Word *word);
void __Word_ShowSourceCode(Word *word);
byte *Word_GetLocalsSourceCodeString(Word *word, byte *buffer);
void _Word_ShowSourceCode(Word *word);
Word *Word_GetFromCodeAddress(byte *address);
Word *Word_GetFromCodeAddress_NoAlias(byte *address);
void _CfrTil_WordName_Run(byte *name);
Word *_CfrTil_Alias(Word *word, byte *name);
void Do_TextMacro(void);
void Do_StringMacro(void);
void _CfrTil_Macro(int64 mtype, byte *function);
Word *Word_GetOriginalWord(Word *word);
/* basis/core/readTable.c */
void CfrTil_ReadTables_Setup(CfrTil *cfrl);
void ReadTable_Default(ReadLiner *rl);
void ReadTable_LParen(ReadLiner *rl);
void ReadTable_Tab(ReadLiner *rl);
void ReadTable_0x03(ReadLiner *rl);
void ReadTable_0x04(ReadLiner *rl);
void ReadTable_CarriageReturn(ReadLiner *rl);
void ReadTable_Newline(ReadLiner *rl);
void ReadTable_Zero(ReadLiner *rl);
void ReadTable_EOF(ReadLiner *rl);
void ReadTable_ESC(ReadLiner *rl);
void ReadTable_LeftBracket(ReadLiner *rl);
void ReadTable_A(ReadLiner *rl);
void ReadTable_B(ReadLiner *rl);
void ReadTable_C(ReadLiner *rl);
void ReadTable_D(ReadLiner *rl);
void ReadTable_F(ReadLiner *rl);
void ReadTable_H(ReadLiner *rl);
void ReadTable_4(ReadLiner *rl);
void ReadTable_3(ReadLiner *rl);
void ReadTable_1(ReadLiner *rl);
void ReadTable_O(ReadLiner *rl);
void ReadTable_Tilde(ReadLiner *rl);
void ReadTable_BackSpace(ReadLiner *rl);
/* basis/bigNum.c */
mpz_t *_BigInt_New(int32 initializer);
void BigInt_Init(void);
void BigInt_Add(void);
void BigInt_PlusEqual(void);
void BigInt_MinusMinus(void);
void BigInt_PlusPlus(void);
void BigInt_Multiply(void);
void BigInt_Power(void);
void BigInt_MultiplyEqual(void);
void BigInt_DivideWithRemainder(void);
void BigInt_DivideEqual_RemainderDiscarded(void);
void BigInt_Subtract(void);
void BigInt_MinusEqual(void);
int32 BigInt_Cmp(void);
void BigInt_LessThanOrEqual(void);
void BigInt_LogicalEquals(void);
void BigInt_LogicalDoesNotEqual(void);
void BigInt_GreaterThan(void);
void BigInt_GreaterThanOrEqual(void);
void BigInt_LessThan(void);
void BigInt_Print(void);
mpf_t *_BigFloat_New(int32 initializer);
void BigFloat_Init(void);
void BigFloat_Precision(void);
void BigFloat_Width(void);
void BigFloat_FPrint(void);
void BigFloat_EPrint(void);
void BigFloat_Add(void);
void BigFloat_Multiply(void);
void BigFloat_Divide(void);
void BigFloat_Power(void);
void BigFloat_Subtract(void);
int32 BigFloat_Cmp(void);
void BigFloat_Equal(void);
void BigFloat_LessThanOrEqual(void);
void BigFloat_GreaterThan(void);
void BigFloat_GreaterThanOrEqual(void);
void BigFloat_LessThan(void);
/* basis/core/_readline.c */
byte *_ReadLine_pb_NextChar(ReadLiner *rl);
byte _ReadLine_NextChar(ReadLiner *rl);
byte _ReadLine_PeekIndexedChar(ReadLiner *rl, int32 offset);
byte ReadLine_PeekNextChar(ReadLiner *rl);
byte _ReadLine_GetNextChar(ReadLiner *rl);
void _ReadLine_EndThisLine(ReadLiner *rl);
byte ReadLine_CurrentReadChar(ReadLiner *rl);
byte *ReadLine_BytePointerToCurrentReadChar(ReadLiner *rl);
byte ReadLine_LastChar(ReadLiner *rl);
byte ReadLine_PeekNextNonWhitespaceChar(ReadLiner *rl);
int ReadLine_IsThereNextChar(ReadLiner *rl);
void ReadLine_UnGetChar(ReadLiner *rl);
void ReadLine_PushChar(ReadLiner *rl, byte c);
void _ReadLine_ShowCharacter(ReadLiner *rl, byte chr);
void ReadLine_ShowCharacter(ReadLiner *rl);
void _ReadLine_SetMaxEndPosition(ReadLiner *rl);
void _ReadLine_SetEndPosition(ReadLiner *rl);
byte _ReadLine_CharAtCursor(ReadLiner *rl);
byte _ReadLine_CharAtACursorPos(ReadLiner *rl, int32 pos);
void _ReadLine_CursorToEnd(ReadLiner *rl);
void _ReadLine_CursorToStart(ReadLiner *rl);
void _ReadLine_CursorRight(ReadLiner *rl);
void _ReadLine_CursorLeft(ReadLiner *rl);
/* basis/core/array.c */
ByteArray *_ByteArray_AppendSpace_MakeSure(ByteArray *ba, int32 size);
byte *_ByteArray_AppendSpace(ByteArray *ba, int32 size);
void _ByteArray_UnAppendSpace(ByteArray *ba, int32 size);
void _ByteArray_DataClear(ByteArray *ba);
void _ByteArray_Init(ByteArray *ba);
int32 ByteArray_IsAddressWwitinTheArray(ByteArray *ba, byte *address);
void _ByteArray_ReInit(ByteArray *ba);
ByteArray *ByteArray_Init(ByteArray *ba, int32 size, uint32 type);
ByteArray *ByteArray_AllocateNew(int32 size, uint32 type);
byte *_ByteArray_GetEndIndex(ByteArray *ba);
byte *_ByteArray_Here(ByteArray *ba);
void _ByteArray_SetEndIndex(ByteArray *ba, byte *index);
void _ByteArray_SetHere(ByteArray *ba, byte *index);
void _ByteArray_SetHere_AndForDebug(ByteArray *ba, byte *index);
byte *_ByteArray_GetStartIndex(ByteArray *ba);
void _ByteArray_SetStartIndex(ByteArray *ba, byte *index);
void ByteArray_AppendCopyItem(ByteArray *ba, int32 size, int32 data);
void ByteArray_AppendCopy(ByteArray *ba, int32 size, byte *data);
void ByteArray_AppendCopyUpToRET(ByteArray *ba, byte *data);
ByteArray *_NamedByteArray_AddNewByteArray(NamedByteArray *nba, int32 size);
NamedByteArray *_NamedByteArray_Allocate(int32 allocType);
NamedByteArray *NamedByteArray_Allocate(void);
void _NamedByteArray_Init(NamedByteArray *nba, byte *name, int32 size, int32 atype);
void NamedByteArray_Delete(NamedByteArray *nba);
NamedByteArray *NamedByteArray_New(byte *name, int32 size, int32 atype);
int32 NamedByteArray_CheckAddress(NamedByteArray *nba, byte *address);
/* basis/core/compiler.c */
void Compiler_IncrementCurrentAccumulatedOffset(Compiler *compiler, int32 increment);
void Compiler_SetCurrentAccumulatedOffsetValue(Compiler *compiler, int32 value);
NamedByteArray *_Compiler_SetCompilingSpace(byte *name);
byte *_Compiler_GetCodeSpaceHere(void);
void Compiler_SetCompilingSpace(byte *name);
void _Compiler_SetCompilingSpace_MakeSureOfRoom(byte *name, int32 room);
void Compiler_SetCompilingSpace_MakeSureOfRoom(byte *name);
void Compiler_Show_WordList(byte *prefix);
Word *Compiler_PreviousNonDebugWord(int startIndex);
void _Compiler_FreeLocalsNamespace(Compiler *compiler);
void _Compiler_FreeAllLocalsNamespaces(Compiler *compiler);
Word *Compiler_WordList(int32 n);
void _CompileOptInfo_Init(Compiler *compiler);
void CompileOptInfo_Init(Compiler *compiler);
CompileOptimizeInfo *CompileOptInfo_New(Compiler *compiler, uint32 type);
void CompileoptInfo_Delete(CompileOptimizeInfo *optInfo);
void CfrTil_InitBlockSystem(Compiler *compiler);
void Compiler_Init(Compiler *compiler, uint64 state);
Compiler *Compiler_New(uint32 type);
void CfrTil_CalculateAndSetPreviousJmpOffset(byte *jmpToAddress);
void CfrTil_CalculateAndSetPreviousJmpOffset_ToHere(void);
void _Stack_PointerToJmpOffset_Set(byte *address);
void Stack_PointerToJmpOffset_Set(void);
void _Compiler_CompileAndRecord_PushEAX(Compiler *compiler);
/* basis/core/dllnodes.c */
/* basis/core/finder.c */
Symbol *_Word_FindSymbol_InOneNamespace(dllist *list, uint64 state, byte *name);
Word *Word_FindInOneNamespace(Namespace *ns, byte *name);
Word *_Word_Find(uint64 state, byte *name);
Word *Word_FindUsing(byte *name);
Word *_Word_FindAny(byte *name);
Word *Word_Find(byte *name);
void Finder_Init(Finder *finder);
Finder *Finder_New(uint32 allocationType);
Symbol *_Finder_CompareDefinitionAddress(Symbol *symbol, byte *address);
Symbol *_Finder_CompareDefinitionAddress_NoAlias(Symbol *symbol, byte *address);
Word *Finder_Address_FindInOneNamespace(Finder *finder, Namespace *ns, byte *address);
Word *Finder_Address_FindAny(Finder *finder, byte *address);
Word *Finder_Address_FindAny_NoAlias(Finder *finder, byte *address);
void Finder_SetQualifyingNamespace(Finder *finder, Namespace *ns);
void Finder_SetNamedQualifyingNamespace(Finder *finder, byte *name);
Namespace *Finder_GetQualifyingNamespace(Finder *finder);
Word *Finder_Word_FindUsing(Finder *finder, byte *name, int32 saveQns);
Word *Finder_FindQualifiedIDWord(Finder *finder, byte *token);
byte *Finder_GetTokenDefinitionAddress(Finder *finder, byte *token);
Word *Finder_FindToken_WithException(Finder *finder, byte *token);
Word *Finder_FindToken(Finder *finder, byte *token);
Word *_CfrTil_FindInAnyNamespace(byte *name);
Word *_CfrTil_Token_FindUsing(byte *token);
void CfrTil_Token_Find(void);
void CfrTil_Find(void);
void CfrTil_Postfix_Find(void);
/* basis/core/interpreters.c */
void _Interpret_ListNode(dlnode *node);
void _Interpret_String(byte *str);
byte *_Interpret_C_Until_EitherToken(Interpreter *interp, byte *end1, byte *end2, byte *delimiters);
byte *_Interpret_Until_Token(Interpreter *interp, byte *end, byte *delimiters);
void _Interpret_PrefixFunction_Until_Token(Interpreter *interp, Word *prefixFunction, byte *end, byte *delimiters);
void _Interpret_PrefixFunction_Until_RParen(Interpreter *interp, Word *prefixFunction);
void _Interpret_UntilFlagged(Interpreter *interp, int32 doneFlags);
void _Interpret_ToEndOfLine(Interpreter *interp);
void Interpret_UntilFlaggedWithInit(Interpreter *interp, int32 doneFlags);
void _CfrTil_Interpret(CfrTil *cfrTil);
void CfrTil_InterpreterRun(void);
/* basis/tabCompletion.c */
void RL_TabCompletion_Run(ReadLiner *rl, Word *rword);
TabCompletionInfo *TabCompletionInfo_New(uint32 type);
byte *ReadLiner_GenerateFullNamespaceQualifiedName(ReadLiner *rl, Word *w);
Boolean _TabCompletion_Compare(Word *word);
int32 _TC_FindPrevious_NamespaceQualifiedIdentifierStart(TabCompletionInfo *tci, byte *s, int32 pos);
void RL_TC_StringInsert_AtCursor(ReadLiner *rl, byte *strToInsert);
byte *_TabCompletionInfo_GetAPreviousIdentifier(ReadLiner *rl, int32 start);
void RL_TabCompletionInfo_Init(ReadLiner *rl);
/* basis/colors.c */
void _OpenVmTil_ColorsInit(OpenVmTil *ovt);
void Console(void);
void _ShowRGB(int fr, int fg, int fb, int br, int bg, int bb);
void _String_ShowRGB(byte *buf, int fr, int fg, int fb, int br, int bg, int bb);
void _ShowRgbColors(Colors *c);
void _String_ShowRgbColors(byte *buf, Colors *c);
void Colors_Init6(Colors *c, int fr, int fg, int fb, int br, int bg, int bb);
void ShowColors(Colors *c);
void String_ShowColors(byte *buf, Colors *c);
void _Colors_Init2(Colors *c, int fg, int bg);
void _CfrTil_SetRGBColor(Colors *c);
void _CfrTil_SetColors(Colors *c);
void Ovt_UserColors(void);
void Ovt_AlertColors(void);
void Ovt_DefaultColors(void);
void Ovt_DebugColors(void);
void Ovt_NoticeColors(void);
void CfrTil_SetDefaultColors(void);
void CfrTil_SetAlertColors(void);
void CfrTil_SetDebugColors(void);
void CfrTil_SetUserColors(void);
void CfrTil_SetNoticeColors(void);
void CfrTil_SetDefaultRGB(void);
void CfrTil_SetUserRGB(void);
void CfrTil_SetAlertRGB(void);
void CfrTil_SetDebugRGB(void);
void CfrTil_SetNoticeRGB(void);
/* basis/sourceCode.c */
void DWL_ShowNode(dlnode *node, byte *insert);
void DebugWordList_Show(void);
byte *PrepareSourceCodeString(dobject *dobj, Word *scWord, Word *word, int32 scwi0);
node *DWL_Check_SCI(dlnode *node, byte *address, int32 scwi, Word *wordn, dlnode **maybeFoundNode, int32 *diff1);
node *DWL_Find(Word *word, byte *address, byte *name, int32 fromFirst, int32 takeFirstFind, byte *newAddress);
void _Debugger_ShowSourceCodeAtAddress(Debugger *debugger);
void _CfrTil_AdjustSourceCodeAddress(byte *address, byte *newAddress);
void _DWL_CheckPush_Word(Word *word);
void DWL_CheckPush_Word(void);
void SC_DWL_PushCWL_Index(int32 index);
dobject *DebugWordList_PushWord(Word *word);
void CfrTil_DebugWordList_Pop(void);
void CfrTil_WordList_Pop(void);
void _CfrTil_WordLists_PushWord(Word *word);
void CfrTil_WordLists_PopWord(void);
void CfrTil_SourceCodeBeginBlock(void);
void CfrTil_SourceCodeEndBlock(void);
void CfrTil_SourceCode_Begin_C_Block(void);
void CfrTil_SourceCode_End_C_Block(void);
/* basis/debugStepping.c */
void _Debugger_DoStepOneInstruction(Debugger *debugger);
void Debugger_StepOneInstruction(Debugger *debugger);
byte *Debugger_CompileOneInstruction(Debugger *debugger, byte *jcAddress);
void _Debugger_CompileAndStepOneInstruction(Debugger *debugger, byte *jcAddress);
int32 Debugger_CanWeStep(Debugger *debugger, Word *word);
byte *_Debugger_CompileOneInstruction(Debugger *debugger, byte *jcAddress);
void Debugger_CompileAndStepOneInstruction(Debugger *debugger);
void Debugger_PreStartStepping(Debugger *debugger);
void Debugger_Step(Debugger *debugger);
void Debugger_AfterStep(Debugger *debugger);
void _Debugger_SetupStepping(Debugger *debugger, Word *word, byte *address, byte *name, int32 iflag);
void Debugger_SetupStepping(Debugger *debugger, int32 iflag);
void CpuState_Compile_SaveStackRegs(Cpu *cpu);
void CpuState_Compile_RestoreStackRegs(Cpu *cpu, int32 esiEdiFlag);
int32 Debugger_SetupReturnStackCopy(Debugger *debugger, int32 size);
void Debugger_Compile_Restore_Runtime_DebuggerCpuState(Debugger *debugger, int32 setupOff, int32 showFlag);
void CfrTil_Compile_RestoreCCompileTimeCpuState(CfrTil *cfrtil, int32 showFlag);
void CfrTil_Compile_SaveCCompileTimeCpuState(CfrTil *cfrtil, int32 showFlag);
void Debugger_Compile_Save_RunTime_DebuggerCpuState(Debugger *debugger, int32 showFlag);
void Debugger_Stepping_Off(Debugger *debugger);
Word *Debugger_GetWordFromAddress(Debugger *debugger);
byte *Debugger_DoJcc(Debugger *debugger, int32 numOfBytes);
void Debug_ExtraShow(int32 size, int32 force);
/* basis/core/string.c */
Boolean IsChar_Dot(byte character);
Boolean IsChar_Whitespace(byte character);
Boolean IsChar_DelimiterOrDot(byte character);
Boolean IsChar_ADotAndNotANonDelimiter(byte character);
void Mem_Clear(byte *buffer, int32 size);
int32 String_IsPreviousCharA_(byte *s, int32 pos, byte c);
int32 String_IsLastCharADot(byte *s, int32 pos);
int32 String_FirstCharOfToken_FromPosOfLastChar(byte *s, int32 pos);
int32 String_IsThereADotSeparatorBackFromPosToLastNonDelmiter(byte *s, int32 pos);
int32 String_LastCharOfLastToken_FromPos(byte *s, int32 pos);
int32 String_FirstTokenDelimiter_FromPos(byte *s, int32 pos);
Boolean String_IsReverseTokenQualifiedID(byte *s, int32 pos);
byte *_String_UnBox(byte *token);
byte *_String_InsertColors(byte *s, Colors *c);
byte *_String_Insert_AtIndexWithColors(byte *token, int ndx, Colors *c);
byte *String_ReadLineToken_HighLight(byte *token);
byte *_String_AppendConvertCharToBackSlashAtIndex(byte *dst, byte c, int32 *index, int32 quoteMode);
byte *_String_AppendConvertCharToBackSlash(byte *dst, byte c);
byte *_String_ConvertStringFromBackSlash(byte *dst, byte *src);
byte String_ConvertEscapeCharToSpace(byte c);
byte *_String_ConvertString_EscapeCharToSpace(byte *dst, byte *src);
byte *String_ConvertString_EscapeCharToSpace(byte *istring);
byte *_String_ConvertStringToBackSlash(byte *dst, byte *src);
byte *String_ConvertToBackSlash(byte *str0);
int32 stricmp(byte *str0, byte *str1);
int32 StrnCmp(byte *str0, byte *str1, int32 n);
int32 StrnICmp(byte *str0, byte *str1, int32 n);
byte *strToLower(byte *dest, byte *str);
void String_RemoveEndWhitespace(byte *string);
byte *String_FilterMultipleSpaces(byte *istring, int32 allocType);
void String_InsertCharacter(CString into, int32 position, byte character);
void String_InsertDataIntoStringSlot(byte *str, int32 startOfSlot, int32 endOfSlot, byte *data);
byte *String_RemoveFinalNewline(byte *astring);
byte *String_N_New(byte *string, int32 n, uint32 allocType);
byte *String_New(byte *string, uint32 allocType);
byte _String_NextNonDelimiterChar(byte *str0, byte *cset);
int32 _CfrTil_StrTok(byte *inBuffer);
byte *StringMacro_Run(byte *pb_namespaceName, byte *str);
byte *_CfrTil_StringMacros_Init(void);
byte *_CfrTil_StringMacros_Do(byte *buffer);
byte *_String_GetStringToEndOfLine(void);
int32 String_FindStrnCmpIndex(byte *sc, byte *name0, int32 *i_ptr, int32 index0, int32 wl0, int32 inc);
byte *String_CheckForAtAdddress(byte *address);
byte *String_CheckGetValueAtAddress(byte *address);
void _Buffer_Clear(Buffer *b);
byte *Buffer_Data_Cleared(Buffer *b);
Buffer *_Buffer_New(int32 size, int32 flag);
void Buffer_SetAsUnused(Buffer *b, int32 force);
void Buffers_SetAsUnused(int32 force);
Buffer *Buffer_New(int32 size);
Buffer *Buffer_NewLocked(int32 size);
Buffer *_Buffer_NewPermanent(int32 size);
byte *Buffer_New_pbyte(int32 size);
/* basis/openVmTil.c */
int main(int argc, char *argv[ ]);
void openvmtil(int argc, char *argv[ ]);
void _OpenVmTil(int argc, char *argv[ ]);
void _OpenVmTil_Run(OpenVmTil *ovt);
OpenVmTil *_OpenVmTil_Allocate(void);
void _OpenVmTil_Init(OpenVmTil *ovt, int resetHistory);
void Ovt_RunInit(OpenVmTil *ovt);
void OpenVmTil_Delete(OpenVmTil *ovt);
void _OpenVmTil_CalculateMemSpaceSizes(OpenVmTil *ovt, int32 restartCondition, int32 totalMemSizeTarget);
void OVT_GetStartupOptions(OpenVmTil *ovt);
OpenVmTil *_OpenVmTil_New(OpenVmTil *ovt, int argc, char *argv[ ], struct termios *savedTerminalAttributes);
void OVT_ShowNBAs(OpenVmTil *ovt, int32 flag);
int32 _OVT_ShowPermanentMemList(OpenVmTil *ovt, int32 flag);
int32 _Calculate_TotalNbaAccountedMemAllocated(OpenVmTil *ovt, int32 flag);
void _OVT_ShowMemoryAllocated(OpenVmTil *ovt);
/* basis/core/dobject.c */
byte *_object_Allocate(int32 size, int32 allocType);
dobject *_dobject_Allocate(int32 doType, int32 slots, uint32 allocType);
dobject *_dobject_New_M_Slot_Node(int32 allocType, int32 dobjType, int m_slots, ...);
void _dobject_Print(dobject *dobj);
void _DObject_C_StartupCompiledWords_DefInit(byte *function, int32 arg);
void _DObject_ValueDefinition_Init(Word *word, uint32 value, uint64 funcType, byte *function, int arg);
void _DObject_Finish(Word *word);
Word *_DObject_Init(Word *word, uint32 value, uint64 ftype, byte *function, int arg, int32 addToInNs, Namespace *addToNs);
Word *_DObject_New(byte *name, uint32 value, uint64 ctype, uint64 ltype, uint64 ftype, byte *function, int arg, int32 addToInNs, Namespace *addToNs, uint32 allocType);
DObject *_DObject_FindSlot_BottomUp(DObject *dobject, byte *name);
DObject *_DObject_SetSlot(DObject *dobject, byte *name, int32 value);
void DObject_SubObjectInit(DObject *dobject, Word *parent);
DObject *DObject_Sub_New(DObject *proto, byte *name, uint64 category);
void CfrTil_SetPropertiesAsDObject(void);
DObject *_DObject_NewSlot(DObject *proto, byte *name, int32 value);
void CfrTil_DObject_Clone(void);
void DObject_NewClone(DObject *proto);
void DObject_New(void);
/* basis/core/memory.c */
/* basis/core/preprocessor.c */
int32 GetOuterBlockStatus(void);
int32 _GetCondStatus(void);
int32 GetIfStatus(void);
int32 GetElxxStatus(int32 cond, int32 type);
int32 GetElifStatus(void);
int32 GetElseStatus(void);
int32 GetEndifStatus(void);
void SkipPreprocessorCode(void);
/* basis/property.c */
/* basis/lists.c */
void List_Interpret(dllist *list);
void List_InterpretLists(dllist *list);
void List_CheckInterpretLists_OnVariable(dllist *list, byte *token);
void _List_PrintNames(dllist *list, int32 count, int32 flag);
void _List_Show_N_Word_Names(dllist *list, uint32 n, int32 showBeforeAfterFlag, int32 dbgFlag);
/* basis/debugDisassembly.c */
ud_t *Debugger_UdisInit(Debugger *debugger);
int32 Debugger_Udis_GetInstructionSize(Debugger *debugger);
int32 Debugger_UdisOneInstruction(Debugger *debugger, byte *address, byte *prefix, byte *postfix);
void _Debugger_Disassemble(Debugger *debugger, byte *address, int32 number, int32 cflag);
void Debugger_Disassemble(Debugger *debugger, byte *format, byte *address);
void Debugger_Dis(Debugger *debugger);
void _Debugger_DisassembleWrittenCode(Debugger *debugger);
void Debugger_DisassembleAccumulated(Debugger *debugger);
void Debugger_DisassembleTotalAccumulated(Debugger *debugger);
/* basis/linux.c */
void _DisplaySignal(int signal);
void Linux_SetupSignals(sigjmp_buf *sjb, int startTimes);
void Linux_RestoreTerminalAttributes(void);
void Linux_SetInputMode(struct termios *savedTerminalAttributes);
void LinuxInit(struct termios *savedTerminalAttributes);
/* basis/exception.c */
int32 _OpenVmTil_ShowExceptionInfo(void);
int32 _OVT_Pause(byte *prompt, int32 signalsHandled);
int32 _OpenVmTil_Pause(byte *msg);
void OpenVmTil_Pause(void);
void _OVT_Throw(int32 restartCondition);
void OpenVmTil_Throw(byte *excptMessage, int32 restartCondition, int32 infoFlag);
void _OpenVmTil_LongJmp_WithMsg(int32 restartCondition, byte *msg);
void OpenVmTil_SignalAction(int signal, siginfo_t *si, void *uc);
void CfrTil_Exception(int32 signal, int32 restartCondition);
void Error3(byte *format, byte *one, byte *two, int three);
void Error2(byte *format, byte *one, int two);
/* basis/types.c */
/* basis/compiler/locals.c */
void _Compiler_AddLocalFrame(Compiler *compiler);
void Compiler_SetLocalsFrameSize_AtItsCellOffset(Compiler *compiler);
void _Compiler_RemoveLocalFrame(Compiler *compiler);
void _Compile_ESP_Restore(void);
void _Compile_ESP_Save(void);
void CfrTil_LocalsAndStackVariablesBegin(void);
void CfrTil_LocalVariablesBegin(void);
void CheckAddLocalFrame(Compiler *compiler);
void CheckCompileRemoveLocalFrame(Compiler *compiler);
/* basis/debugger.c */
void Debugger_TableSetup(Debugger *debugger);
void _Debugger_InterpreterLoop(Debugger *debugger);
void _Debugger_PreSetup(Debugger *debugger, Word *word);
void _Debugger_PostShow(Debugger *debugger);
byte *Debugger_GetStateString(Debugger *debugger);
void Debugger_NextToken(Debugger *debugger);
void Debugger_CurrentToken(Debugger *debugger);
void Debugger_Parse(Debugger *debugger);
void _Debugger_FindAny(Debugger *debugger);
void Debugger_FindAny(Debugger *debugger);
void Debugger_FindUsing(Debugger *debugger);
void Debugger_Variables(Debugger *debugger);
void Debugger_Using(Debugger *debugger);
void Debugger_Eval(Debugger *debugger);
void Debugger_SetupNextToken(Debugger *debugger);
void Debugger_Info(Debugger *debugger);
void Debugger_DoMenu(Debugger *debugger);
void Debugger_Stack(Debugger *debugger);
void Debugger_ReturnStack(Debugger *debugger);
void Debugger_Source(Debugger *debugger);
void _Debugger_CpuState_Show(void);
void Debugger_CpuStateShow(Debugger *debugger);
void Debugger_SaveCpuState(Debugger *debugger);
void CfrTil_Debugger_SaveCpuState(void);
void Debugger_State_Show(Debugger *debugger);
void Debugger_On(Debugger *debugger);
void _Debugger_Off(Debugger *debugger);
void Debugger_Off(Debugger *debugger, int32 debugOffFlag);
void Debugger_Continue(Debugger *debugger);
void Debugger_Quit(Debugger *debugger);
void Debugger_Abort(Debugger *debugger);
void Debugger_Stop(Debugger *debugger);
void Debugger_InterpretLine_WithStartString(byte *str);
void Debugger_InterpretLine(void);
void Debugger_Escape(Debugger *debugger);
void Debugger_AutoMode(Debugger *debugger);
void Debugger_OptimizeToggle(Debugger *debugger);
void Debugger_CodePointerUpdate(Debugger *debugger);
void Debugger_Dump(Debugger *debugger);
void Debugger_Default(Debugger *debugger);
void _Debugger_State(Debugger *debugger);
void _Debugger_Copy(Debugger *debugger, Debugger *debugger0);
Debugger *Debugger_Copy(Debugger *debugger0, uint32 type);
void Debugger_Delete(Debugger *debugger);
void CpuState_AdjustEdi(Cpu *cpu, uint32 *dsp, Word *word);
void Debugger_AdjustEdi(Debugger *debugger, uint32 *dsp, Word *word);
void _Debugger_Init(Debugger *debugger, Word *word, byte *address);
ByteArray *Debugger_ByteArray_AllocateNew(int32 size, uint32 type);
Debugger *_Debugger_New(uint32 type);
void _CfrTil_DebugInfo(void);
void _CfrTil_Debug_AtAddress(byte *address);
void _CfrTil_DebugContinue(int autoFlagOff);
void Debugger_DebugWordListLogic(Debugger *debugger);
/* basis/interpreter.c */
void Interpreter_Init(Interpreter *interp);
Interpreter *Interpreter_New(uint32 type);
void _Interpreter_Copy(Interpreter *interp, Interpreter *interp0);
Interpreter *Interpreter_Copy(Interpreter *interp0, uint32 type);
int32 Interpreter_IsDone(Interpreter *interp, int32 flags);
/* basis/_debug.c */
byte *JccInstructionAddress_2Byte(byte *address);
byte *JccInstructionAddress_1Byte(byte *address);
byte *JumpCallInstructionAddress(byte *address);
void _CfrTil_ACharacterDump(char aChar);
void CfrTil_CharacterDump(byte *address, int32 number);
void _CfrTil_AByteDump(byte aByte);
void CfrTil_NByteDump(byte *address, int32 number);
int32 _IsString(byte *address, int32 maxLength);
byte *IsString(byte *address);
byte *GetPostfix(byte *address, byte *postfix, byte *buffer);
void Compile_Debug_GetESP(void);
void _Compile_DebugRuntimeBreakpoint(void);
/* basis/lambdaCalculus.c */
ListObject *_LO_Eval(ListObject *l0, ListObject *locals, int32 applyFlag);
void LO_Substitute(ListObject *lambdaParameters, ListObject *funcCallValues);
ListObject *_LO_EvalList(ListObject *lorig, ListObject *locals, int32 applyFlag);
ListObject *LO_SpecialFunction(ListObject *l0, ListObject *locals);
ListObject *_LO_Define(byte *sname, ListObject *idNode, ListObject *locals);
ListObject *_LO_Macro(ListObject *l0, ListObject *locals);
ListObject *LO_CompileDefine(ListObject *l0, ListObject *locals);
ListObject *LO_Define(ListObject *l0, ListObject *locals);
ListObject *_LO_Set(ListObject *lfirst, ListObject *locals);
ListObject *LO_Set(ListObject *lfirst, ListObject *locals);
ListObject *LO_Let(ListObject *lfirst, ListObject *locals);
ListObject *_LO_MakeLambda(ListObject *l0);
ListObject *LO_MakeLambda(ListObject *l0);
ListObject *_LO_Cons(ListObject *first, ListObject *second, uint32 allocType);
ListObject *LO_If(ListObject *l0, ListObject *locals);
ListObject *LO_Cond(ListObject *l0, ListObject *locals);
ListObject *_LO_List(ListObject *lfirst);
ListObject *LO_List(ListObject *lfirst);
ListObject *LO_Begin(ListObject *l0, ListObject *locals);
ListObject *LO_Car(ListObject *l0);
ListObject *LO_Cdr(ListObject *l0);
ListObject *_LC_Eval(ListObject *l0);
void _LO_Semi(Word *word);
Word *_LO_Colon(ListObject *lfirst);
ListObject *_LO_CfrTil(ListObject *lfirst);
ListObject *_LO_New_RawStringOrLiteral(Lexer *lexer, byte *token, int32 qidFlag);
ListObject *_LO_New(uint64 ltype, uint64 ctype, byte *value, Word *word, uint32 allocType);
void LO_Quote(void);
void LO_QuasiQuote(void);
void LO_UnQuoteSplicing(void);
void LO_Splice(void);
void LO_UnQuote(void);
void LO_SpliceAtTail(ListObject *lnew, ListObject *l0);
ListObject *_LO_Read(void);
ListObject *LO_PrepareReturnObject(void);
void LO_BeginBlock(void);
void LO_EndBlock(void);
void LO_CheckEndBlock(void);
int32 _LO_CheckBegunBlock(void);
int32 _LO_CheckBeginBlock(void);
int32 LO_CheckBeginBlock(void);
int32 _LO_Apply_Arg(ListObject **pl1, int32 applyRtoL, int32 i);
ListObject *_LO_Apply_ArgList(ListObject *l0, Word *word, int32 applyRtoL);
ListObject *_LO_Apply_C_LtoR_ArgList(ListObject *l0, Word *word);
ListObject *_LO_Apply_A_LtoR_ArgList_For_C_RtoL(ListObject *l0, Word *word);
void LC_CompileRun_C_ArgList(Word *word);
void _Interpreter_LC_InterpretWord(Interpreter *interp, ListObject *l0, Word *word);
void _LO_CompileOrInterpret_One(ListObject *l0);
void _LO_CompileOrInterpret(ListObject *lfunction, ListObject *ldata);
ListObject *_LO_Do_FunctionDataBlock(ListObject *lfunction, ListObject *lfdata);
ListObject *_LO_Apply(ListObject *l0, ListObject *lfunction, ListObject *ldata);
block CompileLispBlock(ListObject *args, ListObject *body);
byte *_LO_PrintOneToString(ListObject *l0, byte *buffer, int in_a_LambdaFlag, int printValueFlag);
byte *_LO_PrintListToString(ListObject *l0, byte *buffer, int lambdaFlag, int printValueFlag);
void LO_Print(ListObject *l0);
ListObject *_LO_First(ListObject *l0);
ListObject *_LO_Last(ListObject *l0);
ListObject *_LO_Next(ListObject *l0);
Word *_LO_FindWord(Namespace *l0, byte *name, ListObject *locals);
ListObject *_LO_AllocCopyOne(ListObject *l0, uint32 allocType);
void _LO_ListInit(ListObject *l0, uint32 allocType);
ListObject *_LO_ListNode_Copy(ListObject *l0, uint32 allocType);
ListObject *_LO_CopyOne(ListObject *l0, uint32 allocType);
ListObject *_LO_Copy(ListObject *l0, uint32 allocType);
Boolean LO_strcat(byte *buffer, byte *buffer2);
void LC_EvalPrint(ListObject *l0);
ListObject *_LO_Read_ListObject(int32 parenLevel);
void _LO_ReadEvalPrint_ListObject(int32 parenLevel, int32 continueFlag);
void LO_ReadEvalPrint_ListObject(void);
void LO_ReadEvalPrint1(void);
void LO_ReadEvalPrint(void);
void LO_ReadInitFile(byte *filename);
void LO_Repl(void);
void LC_PrintWithValue(void);
void LC_Read(void);
void LC_Eval(void);
void LC_DupList(void);
void _LC_SaveStack(LambdaCalculus *lc);
void _LC_ResetStack(LambdaCalculus *lc);
void LC_RestoreStack(void);
void LC_SaveStack(void);
void _LC_Init(LambdaCalculus *lc, int32 newFlag);
void LC_Clear(int32 deleteFlag);
LambdaCalculus *_LC_New(int32 forceInitFlag);
LambdaCalculus *LC_New(void);
/* primitives/strings.c */
void MultipleEscape(void);
void CfrTil_StrLen(void);
void CfrTil_StrCmp(void);
void CfrTil_StrICmp(void);
void CfrTil_StrCat(void);
void CfrTil_StrCpy(void);
void String_GetStringToEndOfLine(void);
/* primitives/bits.c */
void CfrTil_JMP(void);
void CfrTil_Compile_Jcc(void);
void CfrTil_Jcc_Label(void);
void CfrTil_JmpToHere(void);
void CfrTil_BitWise_NOT(void);
void CfrTil_BitWise_NEG(void);
void CfrTil_BitWise_OR(void);
void CfrTil_BitWise_OrEqual(void);
void CfrTil_BitWise_AND(void);
void CfrTil_BitWise_AndEqual(void);
void CfrTil_BitWise_XOR(void);
void CfrTil_BitWise_XorEqual(void);
void CfrTil_ShiftLeft(void);
void CfrTil_ShiftRight(void);
void CfrTil_ShiftLeft_Equal(void);
void CfrTil_ShiftRight_Equal(void);
/* primitives/maths.c */
void CfrTil_Plus(void);
void CfrTil_IncDec(int32 op);
void CfrTil_PlusPlus(void);
void CfrTil_MinusMinus(void);
void CfrTil_PlusEqual(void);
void CfrTil_MinusEqual(void);
void CfrTil_MultiplyEqual(void);
void CfrTil_DivideEqual(void);
void CfrTil_Minus(void);
void CfrTil_Multiply(void);
void CfrTil_Divide(void);
void CfrTil_Mod(void);
int32 _CFib(int n);
void CFib(void);
void CFactorial(void);
int32 _CFactorial(int32 n);
void CFactorial2(void);
void CFactorial3(void);
/* primitives/logics.c */
void CfrTil_LessThan(void);
void CfrTil_LessThanOrEqual(void);
void CfrTil_GreaterThan(void);
void CfrTil_GreaterThanOrEqual(void);
void CfrTil_Equals(void);
void CfrTil_DoesNotEqual(void);
void CfrTil_LogicalNot(void);
void CfrTil_LogicalAnd(void);
void CfrTil_LogicalOr(void);
void CfrTil_LogicalXor(void);
/* primitives/openvmtils.c */
void OpenVmTil_Verbosity(void);
void Ovt_Optimize(void);
void Ovt_Inlining(void);
void Ovt_AutoVar(void);
void Ovt_AutoVarOff(void);
void Ovt_AutoVarOn(void);
void OpenVmTil_HistorySize(void);
void OpenVmTil_DataStackSize(void);
void OpenVmTil_CodeSize(void);
void OpenVmTil_SessionObjectsSize(void);
void OpenVmTil_CompilerTempObjectsSize(void);
void OpenVmTil_ObjectsSize(void);
void OpenVmTil_DictionarySize(void);
void OpenVmTil_Print_DataSizeofInfo(int flag);
void OVT_ShowMemoryAllocated(void);
void OVT_Exit(void);
void _OVT_Ok(int32 promptFlag);
void OVT_Ok(void);
/* primitives/ios.c */
void Fflush(void);
void CfrTil_Kbhit(void);
void _CfrTil_PrintString(byte *string);
void CfrTil_PrintString(void);
void CfrTil_NewLine(void);
void CfrTil_CarriageReturn(void);
void CfrTil_SPACE(void);
void CfrTil_TAB(void);
void _Print_Binary(byte *buffer, int32 n);
void Print_Binary(int32 n, int32 min, int32 max);
void PrintfInt(int32 n);
void CfrTil_PrintInt(void);
void CfrTil_Emit(void);
void CfrTil_Key(void);
void CfrTil_LogOn(void);
void CfrTil_LogAppend(void);
void CfrTil_LogWrite(void);
void CfrTil_LogOff(void);
/* primitives/parsers.c */
void _CfrTil_Tick(void);
void CfrTil_Token(void);
void CfrTil_Tick(void);
void Parse_SkipUntil_Token(byte *end);
void CfrTil_Parse(void);
/* primitives/interpreters.c */
void CfrTil_DoWord(void);
void CfrTil_CommentToEndOfLine(void);
void CfrTil_ParenthesisComment(void);
void CfrTil_If_ConditionalInterpret(void);
void CfrTil_Elif_ConditionalInterpret(void);
void CfrTil_Else_ConditionalInterpret(void);
void CfrTil_Endif_ConditionalInterpret(void);
void CfrTil_PreProcessor(void);
void CfrTil_Define(void);
void CfrTil_Interpreter_IsDone(void);
void CfrTil_Interpreter_Done(void);
void CfrTil_Interpreter_Init(void);
void CfrTil_InterpretNextToken(void);
void CfrTil_Interpret(void);
void CfrTil_InterpretPromptedLine(void);
void CfrTil_InterpretString(void);
void CfrTil_Interpreter_EvalWord(void);
void CfrTil_TokenToWord(void);
void CfrTil_InterpreterStop(void);
dllist *_CfrTil_Interpret_ReadToList(void);
void CfrTil_Interpret_ReadToList(void);
void CfrTil_Interpret_List(void);
/* primitives/namespaces.c */
void Do_Namespace_WithStatus_2(dlnode *node, MapFunction2 nsf, int32 nsStateFlag, int32 one, int32 two);
void _CfrTil_TreeMap(MapSymbolFunction2 msf2, uint64 state, int32 two, int32 three);
void _CfrTil_NamespacesMap(MapSymbolFunction2 msf2, uint64 state, int32 two, int32 three);
void _CfrTil_ForAllNamespaces(MapSymbolFunction2 msf2);
void Namespace_PrettyPrint(Namespace *ns, int32 indentFlag, int32 indentLevel);
void CfrTil_Namespace_New(void);
void _CfrTil_Namespace_NotUsing(byte *name);
void CfrTil_Namespace_NotUsing(void);
void CfrTil_Namespace_UsingFirst(void);
void CfrTil_Namespace_UsingLast(void);
void CfrTil_PrintInNamespace(void);
void CfrTil_Namespaces(void);
void Symbol_SetNonTREED(Symbol *symbol, int32 one, int32 two);
void Symbol_Namespaces_PrintTraverse(Symbol *symbol, int32 containingNamespace, int32 indentLevel);
void Symbol_Namespaces_PrintTraverseWithWords(Symbol *symbol, int32 containingNamespace, int32 indentLevel);
void CfrTil_Namespaces_PrettyPrintTree(void);
void CfrTil_Namespaces_PrettyPrintTreeWithWords(void);
void _Namespace_Symbol_Print(Symbol *symbol, int32 printFlag, int32 str);
byte *_CfrTil_UsingToString(void);
void CfrTil_Using(void);
void _Namespace_RemoveFromUsingListAndClear(Namespace *ns);
void _CfrTil_RemoveNamespaceFromUsingListAndClear(byte *name);
/* primitives/systems.c */
void CfrTil_InitTime(void);
void CfrTil_TimerInit(void);
void CfrTil_Time(void);
void CfrTil_Throw(void);
void _ShellEscape(char *str);
void ShellEscape_Postfix(void);
void shell(void);
void CfrTil_Filename(void);
void CfrTil_Location(void);
void CfrTil_LineNumber(void);
void CfrTil_LineCharacterNumber(void);
void _CfrTil_Version(int flag);
void CfrTil_Version(void);
void CfrTil_SystemState_Print(void);
void _SetEcho(int32 boolFlag);
void CfrTil_Echo(void);
void CfrTil_EchoOn(void);
void CfrTil_EchoOff(void);
void CfrTil_NoOp(void);
void CfrTil_Hex(void);
void CfrTil_Binary(void);
void CfrTil_Decimal(void);
void CfrTil_Dump(void);
void CfrTil_Source_AddToHistory(void);
void CfrTil_Source_DontAddToHistory(void);
void CfrTil_AllocateNew(void);
void CfrTil_SystemBreak(void);
void CfrTil_Quit(void);
void CfrTil_Abort(void);
void CfrTil_DebugStop(void);
void CfrTil_ResetAll(void);
void CfrTil_Restart(void);
void CfrTil_RestartInit(void);
void CfrTil_FullRestart(void);
void CfrTil_WarmInit(void);
void CfrTil_ReturnFromFile(void);
void CfrTil_ShellEscape(void);
void OVT_Mem_ShowAllocated(void);
/* primitives/compilers.c */
void CfrTil_Here(void);
void CompileCall(void);
void CompileACfrTilWord(void);
void CompileInt64(void);
void CompileInt32(void);
void CompileInt16(void);
void CompileByte(void);
void CompileN(void);
GotoInfo *_GotoInfo_Allocate(void);
void GotoInfo_Delete(dlnode *node);
GotoInfo *_CfrTil_CompileCallGotoPoint(uint64 type);
GotoInfo *GotoInfo_New(byte *lname);
void _CfrTil_Goto(byte *lname);
void CfrTil_Goto(void);
void CfrTil_Goto_Prefix(void);
void CfrTil_Label(void);
void CfrTil_Label_Prefix(void);
void CfrTil_Return(void);
void CfrTil_Continue(void);
void CfrTil_Break(void);
void CfrTil_SetupRecursiveCall(void);
void CfrTil_Literal(void);
void CfrTil_Constant(void);
void CfrTil_Variable(void);
void CfrTil_LeftBracket(void);
void CfrTil_RightBracket(void);
void CfrTil_CompileMode(void);
/* primitives/words.c */
void CfrTil_Colon(void);
Word *_CfrTil_SemiColon(void);
void CfrTil_SemiColon(void);
void CfrTil_SourceCodeCompileOff(void);
void AddressToWord(void);
void Word_Definition(void);
void Word_Value(void);
void Word_Xt_LValue(void);
void Word_DefinitionEqual(void);
void CfrTil_Word_Run(void);
void Word_CodeStart(void);
void Word_CodeSize(void);
void Word_Eval(void);
void Word_Finish(void);
byte *_Word_Begin(void);
void Word_Add(void);
void CfrTil_Word_Create(void);
void CfrTil_Word(void);
void CfrTil_Alias(void);
void CfrTil_Eval_C_Rtl_ArgList(void);
void CfrTil_TextMacro(void);
void CfrTil_StringMacro(void);
void Word_Name(void);
void Word_Location(void);
void Word_Namespace(void);
void CfrTil_Keyword(void);
void CfrTil_Immediate(void);
void CfrTil_IsImmediate(void);
void CfrTil_Inline(void);
void CfrTil_Prefix(void);
void CfrTil_C_Prefix(void);
void CfrTil_C_Return(void);
void CfrTil_Void_Return(void);
void CfrTil_EAX_Return(void);
void CfrTil_DebugWord(void);
void _PrintWord(dlnode *node, int32 *n);
void _Words(Symbol *symbol, MapFunction1 mf, int32 n);
void _DoWords(Symbol *symbol, int32 *n);
int32 _CfrTil_PrintWords(int32 state);
void CfrTil_Words(void);
void _Variable_Print(Word *word);
void _PrintVariable(dlnode *node, int32 *n);
void _Variables(Symbol *symbol, MapFunction1 mf, int32 n);
void _PrintVariables(Symbol *symbol, int32 *n);
int32 _CfrTil_PrintVariables(int32 nsStatus);
void CfrTil_Variables(void);
void _CfrTil_NamespaceWords(void);
void CfrTil_NamespaceWords(void);
void CfrTil_AllWords(void);
/* primitives/file.c */
void CfrTil_IncludeFile(void);
int32 _File_Size(FILE *file);
int32 _File_Exists(byte *fname);
byte *_File_ReadToString_(FILE *file);
byte *_File_ReadToString(byte *name);
void File_ReadToString(void);
void File_Open(void);
void File_Close(void);
void File_Read(void);
void File_Write(void);
void File_Seek(void);
void File_Tell(void);
void File_Size(void);
void File_Exists(void);
/* primitives/stacks.c */
void CfrTil_Dsp(void);
void CfrTil_Drop(void);
void CfrTil_DropN(void);
void _CfrTil_Push(int32 value);
void CfrTil_Dup(void);
void CfrTil_NDup(void);
void CfrTil_Pick(void);
void CfrTil_Swap(void);
void CfrTil_PrintNReturnStack(void);
void CfrTil_PrintNDataStack(void);
void CfrTil_PrintReturnStack(void);
void CfrTil_PrintNDataStack_8(void);
void _CfrTil_PrintDataStack(void);
void CfrTil_PrintDataStack(void);
void CfrTil_CheckInitDataStack(void);
void CfrTil_DataStack_Size(void);
/* primitives/debuggers.c */
void CfrTil_Debug_AtAddress(void);
void CfrTil_LocalsShow(void);
void CfrTil_DebugInfo(void);
void CfrTil_DebugOn(void);
void CfrTil_DebugOff(void);
void CfrTil_DebugRuntimeBreakpoint(void);
/* primitives/memory.c */
void CfrTil_Peek(void);
void CfrTil_Poke(void);
void CfrTil_AtEqual(void);
void CfrTil_Store(void);
/* primitives/primitives.c */
/* primitives/contexts.c */
void CfrTil_Contex_New_RunWord(void);
/* primitives/disassembler.c */
void _CfrTil_Word_Disassemble(Word *word);
void _Word_Disassemble(Word *word);
void CfrTil_Word_Disassemble(void);
void Debugger_WDis(Debugger *debugger);
void CfrTil_Disassemble(void);
/* primitives/syntaxes.c */
void CfrTil_InfixModeOff(void);
void CfrTil_InfixModeOn(void);
void CfrTil_PrefixModeOff(void);
void CfrTil_PrefixModeOn(void);
void CfrTil_C_Syntax_Off(void);
void CfrTil_C_Syntax_On(void);
void CfrTil_AddressOf(void);
void CfrTil_C_Semi(void);
void CfrTil_End_C_Block(void);
void CfrTil_Begin_C_Block(void);
Namespace *CfrTil_C_Class_New(void);
void CfrTil_C_Infix_Equal(void);
void CfrTil_If_C_Combinator(void);
void CfrTil_DoWhile_C_Combinator(void);
void CfrTil_For_C_Combinator(void);
void CfrTil_Loop_C_Combinator(void);
void CfrTil_While_C_Combinator(void);
void CfrTil_TypedefStructBegin(void);
void CfrTil_TypedefStructEnd(void);
void _Type_Create(void);
void _CfrTil_TypeDef(void);
/* primitives/cmaths.c */
int32 _CFib_O3(int n);
void CFib_O3(void);
int32 _CFib2_O3(int n);
void CFib2_O3(void);
void CFactorial_O3(void);
int32 _CFactorial_O3(int32 n);
void CFactorial2_O3(void);
void CFactorial3_O3(void);
/* primitives/dataObjectNews.c */
void CfrTil_Class_New(void);
void CfrTil_Class_Value_New(void);
void CfrTil_Class_Clone(void);
void CfrTil_DObject_New(void);
Namespace *CfrTil_Property_New(void);
void CfrTil_Propertydef(void);
